
pageImages:
  p02:
    - p02a_cen_t01_t01_60_cas.png
    - p02a_cen_t01_t01_60_eus.png
    - p02b_cen_t01_t01_80_cas.png
    - p02b_cen_t01_t01_80_eus.png
  p03:
    - p03a_cen_t03_t03_80_cas.png
    - p03a_cen_t03_t03_80_eus.png
  p04:
    - p04a_cen_t03_t03_60_img.png
    - p04b_cen_t06_t06_80_cas.png
    - p04b_cen_t06_t06_80_eus.png
  p05:
    - p05a_cen_t02_t02_80_img.png
  p06:
    - p06a_cen_t02_t02_90_img.png
  p07:
    - p07a_cen_t02_t02_60_cas.png
    - p07a_cen_t02_t02_60_eus.png
  p08:
    - p08a_cen_t03_t03_60_cas.png
    - p08a_cen_t03_t03_60_eus.png
  p09:
    - p09a_cen_t03_t03_90_img.png
  p10:
    - p10a_cen_t02_t02_90_cas.png
    - p10a_cen_t02_t02_90_eus.png
  p11:
    - p11a_cen_t02_t02_100_img.png
  p12:
    - p12a_cen_t01_t01_100_cas.png
    - p12a_cen_t01_t01_100_img.png
  p13:
    - p13a_cen_t01_t01_60_img.png
  p15:
    - p15a_cen_t02_t02_70_img.png
  p16:
    - p16a_cen_t02_t02_80_cas.png
    - p16a_cen_t02_t02_80_eus.png
  p17:
    - p17a_cen_t02_t02_80_img.png
  p18:
    - p18b_cen_t01_t01_60_img.jpg
    
pageItemNumbers:


pageTitles: # All centered texts' codes
  - p00a_t01
  - p00a_t02
  - p00a_t04
  - p00b_t01
  - p01a_t01
  - p01a_t04
  - p02a_t01
  - p03a_t01
  - p04a_t01
  - p05a_t01
  - p06a_t01
  - p07a_t01
  - p08a_t01
  - p09a_t01
  - p10a_t01
  - p11a_t01
  - p12a_t01
  - p13a_t01
  - p14a_t01
  - p15a_t01
  - p16a_t01
  - p17a_t01
  - p18b_t01

pageItemNumbers:
  01: p01b_t01
  02: p01b_t06
  03: p02b_t01
  04: p03b_t01
  05: p04b_t01
  06: p04b_t06
  07: p05b_t01
  08: p06b_t01
  09: p06b_t06
  10: p07b_t01
  11: p08b_t01
  12: p08b_t06
  13: p09b_t01
  14: p10b_t01
  15: p11b_t01
  16: p12b_t01
  17: p13b_t01
  18: p14b_t01
  19: p15b_t01
  20: p16b_t01
  21: p17b_t01 
  
pageTextReplaces:
  p09:
    p09b_t03:
      parameters: {  }
      template: 'partial/fields/board-input.html.twig'
    p09b_t04:
      parameters: {  }
      template: 'partial/fields/board-input.html.twig'
    p09b_t05:
      parameters: {  }
      template: 'partial/fields/board-input.html.twig'
    p09b_t06:
      parameters: {  }
      template: 'partial/fields/board-input.html.twig'
    p09b_t07:
      parameters: {  }
      template: 'partial/fields/board-input.html.twig'
      
pageAreaWidths:
  p18:
    b: 100

# TODO: being dynamic
totalPages: 18  # The final total pages