p00:
  text:
    - p00a_t03
    - p00a_t04
    - p00a_t05
    - p00a_t06
    - p00a_t07
    - p00a_t08
    - p00a_t09
    - p00b_t02
    - p00b_t03
    - p00b_t04
    - p00b_t05
    - p00b_t06
    - p00b_t07
    - p00b_t08
        
p01:
  text:
    - p01a_t02
    - p01a_t03
    - p01a_t04
    - p01a_t05
    - p01a_t06
    - p01a_t07
    - p01a_t08
  simple:
    - p01b_t02
    - p01b_t03
    - p01b_t04
    - p01b_t05
    - p01b_t08
    - p01b_t09
    - p01b_t10
    - p01b_t11
    
p02:
  simple:
    - p02b_t02
    - p02b_t03
    - p02b_t04
    - p02b_t05
   
p03:
  text:
    - p03a_t03
  simple:
    - p03b_t02
    - p03b_t03
    - p03b_t04
    - p03b_t05
        
p04:
  text:
    - p04a_t02
    - p04a_t03 
  simple:
    - p04b_t02
    - p04b_t03
    - p04b_t04
    - p04b_t05
    - p04b_t07
    - p04b_t08
    - p04b_t09
    - p04b_t10
    
p05:
  text:
    - p05a_t02
  simple:
    - p05b_t02
    - p05b_t03
    - p05b_t04
    - p05b_t05
          
p06:
  text:
    - p06a_t02
  simple:
    - p06b_t01
    - p06b_t02
    - p06b_t03
    - p06b_t04
    - p06b_t08
    - p06b_t09
    - p06b_t10
    - p06b_t11
    
p07:
  text:
    - p07a_t02
  simple:
    - p07b_t02
    - p07b_t03
    - p07b_t04
    - p07b_t05
    
p08:
  text:
    - p08a_t02
    - p08a_t03
  simple:
    - p08b_t02
    - p08b_t03
    - p08b_t04
    - p08b_t05
    - p08b_t08
    - p08b_t09
    - p08b_t10
    - p08b_t11

p09:
  text:
    - p09a_t02
    - p09a_t03
  libre:
    - p09b_t03
    - p09b_t04
    - p09b_t05
    - p09b_t06
    - p09b_t07
   
p10:
  text:
    - p10a_t02
  simple:
    - p10b_t02
    - p10b_t03
    - p10b_t04
    - p10b_t05
   
p11:
  text:
    - p11a_t02
  simple:
    - p11b_t02
    - p11b_t03
    - p11b_t04
    - p11b_t15
        
p12:
  simple:
    - p12b_t02
    - p12b_t03
    - p12b_t04
    - p12b_t05
        
p13:
  text:
    - p13a_t02
    - p13a_t03
  simple:
    - p13b_t02
    - p13b_t03
    - p13b_t04
    - p13b_t05
    
p14:
  text:
    - p14a_t02
    - p14a_t03
    - p14a_t04
  simple:
    - p14b_t02
    - p14b_t03
    - p14b_t04
    - p14b_t05
    
p15:
  text:
    - p15a_t02
  simple:
    - p15b_t02
    - p15b_t03
    - p15b_t04
    - p15b_t05

p16:
  text:
    - p16a_t02
  simple:
    - p16b_t02
    - p16b_t03
    - p16b_t04
    - p16b_t05
    
p17:
  text:
    - p17a_t02
    - p17a_t03
    - p17a_t04
  multiple:
    - p17b_t02
    - p17b_t03
    - p17b_t04
        
