pageAudios:
  p01:
    - p01a_cen_t05_t05_x3_cas.ogg
    - p01a_cen_t05_t05_x3_eus.ogg
  p02:  
    - p02a_cen_t05_t05_x3_cas.ogg
    - p02a_cen_t05_t05_x3_eus.ogg
  p03:  
    - p03a_cen_t05_t05_x3_cas.ogg
    - p03a_cen_t05_t05_x3_eus.ogg
  p04:
    - p04a_cen_t05_t05_x3_cas.mp3
    - p04a_cen_t05_t05_x3_eus.mp3
    - p04a_cen_t05_t05_x3_cas.ogg
    - p04a_cen_t05_t05_x3_eus.ogg  
   
pageImages:
  p01:
    - p01a_cen_t02_t02_50_img.png
  p02:
    - p02a_cen_t01_t01_33_img.png
  p03:
    - p03a_cen_t01_t01_33_img.png
  p04:
    - p04a_cen_t01_t01_50_img.png
  p05:
    - p05b_cen_t01_t01_33_img.png
  p06:
    - p06a_cen_t02_t02_100_img.png
  p07:
    - p07a_cen_t02_t02_30_img.png

pageReplaces:
 
pageTitles:
  - p00a_t01
  - p00a_t02
  - p00b_t01
  - p01a_t01
  - p01a_t03
  - p01a_t07
  - p01a_t08
  - p02a_t00
  - p02a_t01
  - p03a_t00
  - p03a_t01
  - p04a_t01
  - p05b_t01
  - p06a_t01
  - p06a_t02
  - p07a_t01
  - p07a_t02
  - p08a_t01
  - p09a_t01
  - p10a_t01
 
pageAreaWidths:
  p05:  # Page affected with any custom side-width
    b: 100  # side-letter: window-relative-width-percentage
totalPages: 11