pageAudios:
  p01:
    - p01a_cen_t05_t05_x3_cas.ogg
    - p01a_cen_t05_t05_x3_eus.ogg
  p02:  
    - p02a_cen_t05_t05_x3_cas.ogg
    - p02a_cen_t05_t05_x3_eus.ogg
  p03:  
    - p03a_cen_t05_t05_x3_cas.ogg
    - p03a_cen_t05_t05_x3_eus.ogg
  p04:
    - p04a_cen_t05_t05_x3_cas.mp3
    - p04a_cen_t05_t05_x3_eus.mp3
    - p04a_cen_t05_t05_x3_cas.ogg
    - p04a_cen_t05_t05_x3_eus.ogg  
   
pageImages:
  p01:
    - p01a_cen_t02_t02_50_img.png
  p02:
    - p02a_cen_t01_t01_33_img.png
  p03:
    - p03a_cen_t01_t01_33_img.png
  p04:
    - p04a_cen_t01_t01_50_img.png
  p05:
    - p05b_cen_t01_t01_33_img.png
  p06:
    - p06a_cen_t02_t02_100_img.png
  p07:
    - p07a_cen_t02_t02_30_img.png
    - p07a_dch_t07_t08_50_img.png
    - p07a_dch_t12_t14_50_img.png
  p08:
    - p08a_cen_t01_t01_100_img.png
    - p08a_dch_t07a_t09a_33_img.png
    - p08a_dch_t06b_t08b_33_img.png
    
  p09:
    - p09a_cen_t02_t02_100_img.png
  p10:
    - p10a_izq_t03_t05_20_img.png
    - p10a_cen_t07_t07_100_img.png
  p11:
    - p11b_cen_t01_t01_60_img.jpg
  

pageReplaces:
 
pageTitles:
  - p00a_t01
  - p00a_t02
  - p00b_t01
  - p01a_t01
  - p01a_t07
  - p01a_t08
  - p02a_t00
  - p02a_t01
  - p03a_t00
  - p03a_t01
  - p04a_t01
  - p05b_t01
  - p06a_t02
  - p07a_t02
  - p08a_t02
  - p09a_t02
  - p10a_t02
  - p11b_t03
 
pageAreaWidths:
  p05:  # Page affected with any custom side-width
    b: 100  # side-letter: window-relative-width-percentage
  p11:  
    b: 100   
# TODO: being dynamic    
totalPages: 11  # The final total pages