
pageImages:
  p01:  # Page where any image's being show
    - p01a_cen_t06_t06_100_cas.png
    - p01a_cen_t06_t06_100_eus.png
  p02:
    - p02a_cen_t03_t03_100_cas.png
    - p02a_cen_t03_t03_100_eus.png
  p03:
    - p03a_cen_t02_t02_50_img.png
  p04:
    - p04a_cen_t02_t02_75_cas.png
    - p04a_cen_t02_t02_75_eus.png
  p05:
    - p05a_cen_t03_t03_100_cas.png
    - p05a_cen_t03_t03_100_eus.png
  p07:
    - p07a_cen_t01_t01_100_cas.png
    - p07a_cen_t01_t01_100_eus.png
  p08:
    - p08a_cen_t11_t11_40_img.png
  p09:
    - p09a_cen_t01_t01_100_cas.png
    - p09a_cen_t01_t01_100_eus.png
  p10:
    - p10a_cen_t04_t04_50_img.png
  p11:
    - p11a_dch_t03_t09_40_img.png
  p12:
    - p12a_cen_t02_t02_100_cas.png
    - p12a_cen_t02_t02_100_eus.png
  p13:
    - p13a_cen_t02_t02_100_cas.png
    - p13a_cen_t02_t02_100_eus.png
  p15:
    - p15a_cen_t02_t02_100_cas.png
    - p15a_cen_t02_t02_100_eus.png
  p16:
    - p16a_cen_t01_t01_75_img.png
  p17:
    - p17a_cen_t01_t01_75_img.png
  p18:
    - p18a_cen_t02_t02_75_img.png
  p20:
    - p20a_cen_t03_t03_50_img.png
  p21:
    - p21a_cen_t02_t02_80_img.png
  p22:
    - p22a_cen_t02_t02_100_cas.png
    - p22a_cen_t02_t02_100_eus.png
  p23:
    - p23a_cen_t06_t06_75_img.png
  p24:
    - p24a_cen_t02_t02_80_img.png
    - p24b_cen_t06_t06_75_img.png
  p25:
    - p25a_cen_t02_t02_50_img.png
  p26:
    - p26a_cen_t02_t02_75_img.png
  p27:
    - p27a_cen_t07_t07_100_cas.png
    - p27a_cen_t07_t07_100_eus.png
  p28:
    - p28a_cen_t02_t02_75_img.png
  p29:
    - p29b_cen_t01_t01_60_img.jpg

pageTitles: # All centered texts' codes
  - p00b_t01
  - p01a_t01
  - p02a_t01
  - p03a_t01
  - p04a_t01
  - p05a_t01
  - p06a_t01
  - p07a_t01
  - p08a_t01
  - p09a_t01
  - p10a_t01
  - p11a_t01
  - p11a_t02
  - p11a_t03
  - p12a_t01
  - p13a_t01
  - p14a_t01
  - p15a_t01
  - p16a_t01
  - p17a_t01
  - p18a_t01
  - p19a_t01
  - p20a_t01
  - p21a_t01
  - p22a_t01
  - p23a_t01
  - p24a_t01
  - p25a_t01
  - p26a_t01
  - p27a_t01
  - p28a_t01


pageAreaWidths:
  p00:  # Page affected with any custom side-width
    b: 100  # side-letter: window-relative-width-percentage
  p05:
    a: 60
    b: 40
  p07:
    a: 60
    b: 40
  p09:
    a: 60
    b: 40
  p12:
    a: 60
    b: 40
  p13:
    a: 60
    b: 40
  p14:
    a: 60
    b: 40
  p22:
    a: 60
    b: 40
  p23:
    a: 60
    b: 40
  p29:
    b: 100

totalPages: 29  # The final total pages