
pageAudios:
  p01:
    - p01a_cen_t09_t09_x3_cas.ogg
  p02:
    - p02a_cen_t03_t03_x3_cas.ogg
  p03:
    - p03a_cen_t03_t03_x3_cas.ogg

pageImages:
  p00:
    - p00a_izq_t03_t04_30_img.png

  p01:
    - p01a_cen_t08_t08_50_img.png
    - p01a_cen_t09_t09_30_img.jpg
  p02:
    - p02a_cen_t02_t02_33_img.jpg
    - p02a_cen_t03_t03_30_img.jpg
  p03:
    - p03a_cen_t02_t02_90_img.png
    - p03a_cen_t03_t03_30_img.jpg
  p04:
    - p04a_izq_t05_t06_40_img.png
  p05:
    - p05a_izq_t03_t04_40_img.png
  p06:
    - p06a_cen_t02_t02_50_img.png
  p07:
    - p07a_cen_t01_t01_100_img.png
  p08:
    - p08b_cen_t01_t01_60_img.jpg

pageTitles:
  - p00a_t01
  - p01a_t01
  - p01a_t03
  - p01a_t07
  - p01a_t08
  - p02a_t00
  - p02a_t01
  - p02a_t02
  - p03a_t00
  - p03a_t01
  - p03a_t02
  - p04a_t01
  - p04a_t04
  - p05a_t01
  - p05a_t02
  - p06a_t01
  - p06a_t02
  - p07a_t01
  - p08b_t03

pageAreaWidths:
  p07:
    a: 60
    b: 40
  p08:
    b: 100

totalPages: 8