
pageImages:
  p00:
    - p00a_izq_t03_t04_30_img.png
  p01:
    - p01a_cen_t07_t07_50_img.png    
  p02:
    - p02a_cen_t02_t02_50_img.png
  p03:
    - p03b_cen_t02_t02_60_img.png
  p04:
    - p04a_cen_t01_t01_100_img.png
  p05:
    - p05a_cen_t02_t02_100_img.png
  p06:
    - p06a_cen_t02_t02_100_img.png
  p07:
    - p07a_cen_t09_t09_25_img.png
    - p07a_izq_t03_t04_40_img.png
  p08:
    - p08a_cen_t09_t09_25_img.png
    - p08a_izq_t03_t04_40_img.png
  p09:
    - p09a_cen_t09_t09_25_img.png
    - p09a_izq_t03_t04_40_img.png
  p10:
    - p10a_dch_t05_t06_40_img.png
  p11:
    - p11a_dch_t05_t06_40_img.png
  p12:
    - p12a_dch_t05_t06_40_img.png
  p13:
    - p13a_cen_t06_t06_80_img.png
  p14:
    - p14a_cen_t06_t06_80_img.png
  p15:
    - p15b_cen_t01_t01_60_img.jpg

pageReplaces:

pageAudios:
  p01:
    - p01a_cen_t11_t11_x3_cas.mp3
  p02:
    - p02a_cen_t06_t06_x3_cas.mp3
  
pageTitles:
  - p00a_t01
  - p00b_t01
  - p01a_t01
  - p01a_t06
  - p01a_t11
  - p02a_t01
  - p02a_t06
  - p03b_t01
  - p04a_t01
  - p04a_t02
  - p05a_t02
  - p06a_t02
  - p07a_t01
  - p07a_t02
  - p08a_t02
  - p09a_t02
  - p10a_t01
  - p10a_t02
  - p10a_t03
  - p10a_t04
  - p11a_t02
  - p11a_t03
  - p11a_t04
  - p12a_t02
  - p12a_t03
  - p12a_t04
  - p13a_t01
  - p13a_t02
  - p14a_t02
  - p15b_t03

pageAreaWidths:
  p03:  # Page affected with any custom side-width
    b: 100  # side-letter: window-relative-width-percentage
  p15:
    b: 100
  
totalPages: 15
