
pageImages:

  p04:
    - p04a_cen_t03_t03_100_cas.png
    - p04a_cen_t03_t03_100_eus.png
  p05:
    - p05a_cen_t02_t02_90_cas.png
    - p05a_cen_t02_t02_90_eus.png
  p07:
    - p07a_cen_t02_t02_80_img.png
  p08:
    - p08a_cen_t02_t02_60_img.png
  p09:
    - p09a_cen_t02_t02_100_cas.png
    - p09a_cen_t02_t02_100_eus.png
  p10:
    - p10a_cen_t02_t02_100_cas.png
    - p10a_cen_t02_t02_100_eus.png
  p11:
    - p11a_cen_t02_t02_90_img.png
  p12:
    - p12a_cen_t02_t02_90_img.png
  p13:
    - p13a_cen_t03_t03_80_img.png
  p14:
    - p14a_cen_t02_t02_60_img.png
  p15:
    - p15a_cen_t02_t02_90_cas.png
    - p15a_cen_t02_t02_90_eus.png
  p16:
    - p16a_cen_t02_t02_90_cas.png
    - p16a_cen_t02_t02_90_eus.png
  p17:
    - p17a_cen_t02_t02_90_img.jpg
  p18:
    - p18a_cen_t02_t02_60_img.png
  p19:
    - p19a_cen_t03_t03_60_img.png
  p20:
    - p20a_cen_t02_t02_60_img.png
  p21:
    - p21a_cen_t02_t02_80_img.png
  p22:
    - p22a_cen_t02_t02_80_cas.png
    - p22a_cen_t02_t02_80_eus.png
  p23:
    - p23a_cen_t02_t02_80_img.png
  p24:
    - p24a_cen_t02_t02_100_cas.png
    - p24a_cen_t02_t02_100_eus.png
  p25:
    - p25b_cen_t01_t01_60_img.jpg

pageTitles: # All centered texts' codes
  - p00a_t01
  - p00b_t01
  - p01a_t01
  - p02a_t01
  - p03a_t01
  - p04a_t01
  - p05a_t01
  - p06a_t01
  - p07a_t01
  - p08a_t01
  - p09a_t01
  - p10a_t01
  - p11a_t01
  - p12a_t01
  - p13a_t01
  - p14a_t01
  - p15a_t01
  - p16a_t01
  - p17a_t01
  - p18a_t01
  - p19a_t01
  - p20a_t01
  - p21a_t01
  - p22a_t01
  - p23a_t01
  - p24a_t01
  - p25b_t03

pageAreaWidths:
  p00:  # Page affected with any custom side-width
  p19:
    a: 40
    b: 60
  p25:
    b: 100

totalPages: 25  # The final total pages