
pageAudios:
  p01:
    - p01a_cen_t02_t02_x3_eus.ogg
    - p01a_cen_t02_t02_x3_eus.mp3
  p02:
    - p02a_cen_t02_t02_x3_eus.ogg
    - p02a_cen_t02_t02_x3_eus.mp3
  p03:
    - p03a_cen_t02_t02_x3_eus.ogg
    - p03a_cen_t02_t02_x3_eus.mp3

pageImages:
  p00:
    - p00b_cen_t04_t04_50_img.jpg
  p01:
    - p01a_cen_t01_t01_100_img.png
  p02:
    - p02a_cen_t01_t01_100_img.png
  p03:
    - p03a_cen_t01_t01_60_img.jpg
  p04:
    - p04b_cen_t01_t01_60_img.jpg
  p05:
    - p05a_cen_t01_t01_60_img.png
  p06:
    - p06a_cen_t01_t01_60_img.jpg
  p07:
    - p07a_cen_t01_t01_60_img.png
  p08:
    - p08a_cen_t01_t01_60_img.png
    
pageTitles:
  - p00b_t01
  - p00b_t02
  - p00b_t04
  - p01a_t01
  - p02a_t01
  - p03a_t01
  - p04b_t01
  - p05a_t01
  - p06a_t01
  - p07a_t01
  - p08a_t01
  - p09b_t03

pageAreaWidths:
  p00:  
    b: 100  
  p04:
    b: 100
  p09:
    b: 100

totalPages: 10 