
# Database codes' map
codes:
  pilotaje17probak:
    # LH6 Eusk
    lh617_testuak_eus_a:          lh617_eus_a
    lh617_testuak_eus_b:          lh617_eus_b
    lh617_testuak_eus_c:          lh617_eus_c
    # LH6 Gazte
    lh617_testuak_gaz_a:          lh617_gaz_a
    lh617_testuak_gaz_b:          lh617_gaz_b
    lh617_testuak_gaz_c:          lh617_gaz_c
    # LH6 Zie
    lh617_testuak_zie_a:          lh617_zie_a
    lh617_testuak_zie_b:          lh617_zie_b
    lh617_testuak_zie_c:          lh617_zie_c
    # LH6 Mate
    lh617_testuak_mat_a:          lh617_mat_a
    lh617_testuak_mat_b:          lh617_mat_b
    lh617_testuak_mat_c:          lh617_mat_c
    # LH6 Inge
    lh617_testuak_ing_a:          lh617_ing_a
    lh617_testuak_ing_b:          lh617_ing_b
    lh617_testuak_ing_c:          lh617_ing_c
    # DBH4 Eusk
    dbh417_testuak_eus_a:         dbh417_eus_a
    dbh417_testuak_eus_b:         dbh417_eus_b
    dbh417_testuak_eus_c:         dbh417_eus_c
    # DBH4 Gazte
    dbh417_testuak_gaz_a:         dbh417_gaz_a
    dbh417_testuak_gaz_b:         dbh417_gaz_b
    dbh417_testuak_gaz_c:         dbh417_gaz_c
    # DBH4 Zie
    dbh417_testuak_zie_3a:        dbh417_zie_3a
    dbh417_testuak_zie_3b:        dbh417_zie_3b
    dbh417_testuak_zie_bga:       dbh417_zie_bga
    dbh417_testuak_zie_bgb:       dbh417_zie_bgb
    dbh417_testuak_zie_fqa:       dbh417_zie_fqa
    dbh417_testuak_zie_fqb:       dbh417_zie_fqb
    # DBH4 Mate
    dbh417_testuak_mat_a:         dbh417_mat_a
    dbh417_testuak_mat_b:         dbh417_mat_b
    dbh417_testuak_mat_c:         dbh417_mat_c
    # DBH4 Inge
    dbh417_testuak_ing_a:         dbh417_ing_a
    dbh417_testuak_ing_b:         dbh417_ing_b
    dbh417_testuak_ing_c:         dbh417_ing_c
  ed17probak:
    # Eusk
    edg051_testuak_dbh_eusa:      ed17_dbh_eusa
    edg051_testuak_dbh_eusbd:     ed17_dbh_eusbd
    edg051_testuak_lh_eusa:       ed17_lh_eusa
    edg051_testuak_lh_eusbd:      ed17_lh_eusbd
    # Gazte
    edg051_testuak_dbh_gaz:       ed17_dbh_gaz
    edg051_testuak_lh_gaz:        ed17_lh_gaz
    # Inge
    edg051_testuak_dbh_ing:       ed17_dbh_ing
    edg051_testuak_lh_ing:        ed17_lh_ing
    # Mate
    edg051_testuak_dbh_mat:       ed17_dbh_mat
    edg051_testuak_lh_mat:        ed17_lh_mat
    # Zie
    edg051_testuak_dbh_zie:       ed17_dbh_zie
    edg051_testuak_lh_zie:        ed17_lh_zie
    # G. sortak
    edg051_testuak_dbh_gsorta_a:  ed17_dbh_gso_a
    edg051_testuak_dbh_gsorta_b:  ed17_dbh_gso_b
    edg051_testuak_dbh_gsorta_c:  ed17_dbh_gso_c
    edg051_testuak_lh_gsorta_a:   ed17_lh_gso_a
    edg051_testuak_lh_gsorta_b:   ed17_lh_gso_b
    edg051_testuak_lh_gsorta_c:   ed17_lh_gso_c
    # Simul
    edg051_testuak_dbh_simul:     ed17_dbh_simul