
# Database access configuration
credentials:
  pilotaje17probak:
    # LH6 Eusk
    LH6EA17:	lh617_testuak_eus_a
    LH6EB17:	lh617_testuak_eus_b
    LH6EC17:	lh617_testuak_eus_c
    # LH6 Gazte
    LH6CA17:	lh617_testuak_gaz_a
    LH6CB17:	lh617_testuak_gaz_b
    LH6CC17:	lh617_testuak_gaz_c
    # LH6 Zie
    LH6ZA17:	lh617_testuak_zie_a
    LH6ZB17:	lh617_testuak_zie_b
    LH6ZC17:	lh617_testuak_zie_c
    # LH6 Mate
    LH6MA17:	lh617_testuak_mat_a
    LH6MB17:	lh617_testuak_mat_b
    LH6MC17:	lh617_testuak_mat_c
    # LH6 Inge
    LH6IA17:	lh617_testuak_ing_a
    LH6IB17:	lh617_testuak_ing_b
    LH6IC17:	lh617_testuak_ing_c
    # DBH4 Eusk
    DBH4EA17:	dbh417_testuak_eus_a
    DBH4EB17:	dbh417_testuak_eus_b
    DBH4EC17:	dbh417_testuak_eus_c
    # DBH4 Gazte
    DBH4CA17:	dbh417_testuak_gaz_a
    DBH4CB17:	dbh417_testuak_gaz_b
    DBH4CC17:	dbh417_testuak_gaz_c
    # DBH4 Zie
    DBH4Z3A17:	dbh417_testuak_zie_3a
    DBH4Z3B17:	dbh417_testuak_zie_3b
    DBH4ZBGA17:	dbh417_testuak_zie_bga
    DBH4ZBGB17:	dbh417_testuak_zie_bgb
    DBH4ZFQA17:	dbh417_testuak_zie_fqa
    DBH4ZFQB17:	dbh417_testuak_zie_fqb
    # DBH4 Mate
    DBH4MA17:	dbh417_testuak_mat_a
    DBH4MB17:	dbh417_testuak_mat_b
    DBH4MC17:	dbh417_testuak_mat_c
    # DBH4 Inge
    DBH4IA17:	dbh417_testuak_ing_a
    DBH4IB17:	dbh417_testuak_ing_b
    DBH4IC17:	dbh417_testuak_ing_c
  ed17probak:
    # Eusk
    EB2746:
      a:    edg051_testuak_dbh_eusa
      bd:   edg051_testuak_dbh_eusbd
    EL2963:
      a:    edg051_testuak_lh_eusa
      bd:   edg051_testuak_lh_eusbd
    # Gazte
    CB3736: edg051_testuak_dbh_gaz
    CL2528: edg051_testuak_lh_gaz
    # Inge
    IB3896: edg051_testuak_dbh_ing
    IL8027: edg051_testuak_lh_ing
    # Mate
    MB0406: edg051_testuak_dbh_mat
    ML4612: edg051_testuak_lh_mat
    # Zie
    ZB6432: edg051_testuak_dbh_zie
    ZL2428: edg051_testuak_lh_zie
    # G. sortak
    GB3479:
      a:    edg051_testuak_dbh_gsorta_a
      b:    edg051_testuak_dbh_gsorta_b
      c:    edg051_testuak_dbh_gsorta_c
    GL0615:
      a:    edg051_testuak_lh_gsorta_a
      b:    edg051_testuak_lh_gsorta_b
      c:    edg051_testuak_lh_gsorta_c
    # Simul
    SB2017: edg051_testuak_dbh_simul