# Do not repeat variable names that are in 'common', neither the ones that are shared blocks' like 'home' and 'login'.
common:
    course: '2017'
    title:
        eu: 'Ebaluazio diagnostikoa'
        es: 'Evaluación diagnóstica'
        en: ''
home:
    bg_url: '/irudiak/ed_ikasleak1.jpg'
    logo_url: '/irudiak/logoed1.jpg'
    logo_url_footer: 'irudiak/logo_hezkuntza.png'
login:
    title_label: 'Identifikazioa / Identificación'
    form_action: '/board'
    code: 'Ikaslearen kodea / Código del alumno-a'
    bdate: 'Jaiotze data / Fecha nacimiento'
    bday: 'Eguna / Día'
    bmonth: 'Hilabetea / Mes'
    jan: 'urtarrila / enero'
    feb: 'otsaila / febrero'
    mar: 'martxoa / marzo'
    apr: 'apirila / abril'
    may: 'maiatza / mayo'
    jun: 'ekaina / junio'
    jul: 'uztaila / julio'
    aug: 'abuztua / agosto'
    sep: 'iraila / septiembre'
    oct: 'urria / octubre'
    nov: 'azaroa / noviembre'
    dec: 'abendua / diciembre'
    codpro: 'Probaren kodea / Código de la prueba'
    audio_sample_tip: 'Audio proba / Prueba de audio'
    audio_sample_url:
        mp3: ''
        ogg: '/audioak/audio_proba_labur.ogg'
    submit_text: 'Bidali / Enviar'
board:
    title_lh:
        eu: 'LHko ebaluazio probak'
        es: 'Pruebas de evaluación de EP'
        en: ''
    title_dbh:
        eu: 'DBHko ebaluazio probak'
        es: 'Pruebas de evaluación de la ESO'
        en: ''