# Don't repeat fields in each block
index:
    course: '2017'
    bg_url: '/irudiak/ed_ikasleak1.jpg'
    logo_url: '/irudiak/logoed1.jpg'
    logo_url_footer: 'irudiak/logo_hezkuntza.png'
    title:
        eu: 'Ebaluazio diagnostikoa'
        es: 'Evaluación diagnóstica'
        en: ''
    title_lh:
        eu: 'LHko ebaluazio probak'
        es: 'Pruebas de evaluación de EP'
        en: ''
    title_dbh:
        eu: ''
        es: ''
        en: ''
login:
    title_label: 'Identifikazioa | Identificación'
    form_action: ''
    code: 'Ikaslearen kodea | Código del alumno-a'
    bdate: 'Jaiotze data | Fecha nacimiento'
    bday: 'Eguna | Día'
    bmonth: 'Hilabetea | Mes'
    jan: 'urtarrila | enero'
    feb: 'otsaila | febrero'
    mar: 'martxoa | marzo'
    apr: 'apirila | abril'
    may: 'maiatza | mayo'
    jun: 'ekaina | junio'
    jul: 'uztaila | julio'
    aug: 'abuztua | agosto'
    sep: 'iraila | septiembre'
    oct: 'urria | octubre'
    nov: 'azaroa | noviembre'
    dec: 'abendua | diciembre'
    codpro: 'Probaren kodea | Código de la prueba'
    audio_sample: 'Audio proba | Prueba de audio'
    audio_sample_url: '0_audio_proba_labur.ogg'
    audio_sample_img: '/irudiak/play1.jpg'
    submit_text: 'Bidali | Enviar'