
# Routes configuration
routes:
  - /sample
  - { path: /, methods: [GET] }
  - { path: /boarding, methods: [POST] }
  - { path: '/{page}', controller: 'App\Controller\ContentRenderController::pageAction', name: onboard, methods: [POST], requirements: { page: \d+ } }
