
# Database tables' map
targets:
  pilotaje17probak:
    # LH6 Eusk
    lh617_testuak_eus_a:          erantzunak_lh6_eus_a
    lh617_testuak_eus_b:          erantzunak_lh6_eus_b
    lh617_testuak_eus_c:          erantzunak_lh6_eus_c
    # LH6 Gazte
    lh617_testuak_gaz_a:          erantzunak_lh6_gaz_a
    lh617_testuak_gaz_b:          erantzunak_lh6_gaz_b
    lh617_testuak_gaz_c:          erantzunak_lh6_gaz_c
    # LH6 Zie
    lh617_testuak_zie_a:          erantzunak_lh6_zie_a
    lh617_testuak_zie_b:          erantzunak_lh6_zie_b
    lh617_testuak_zie_c:          erantzunak_lh6_zie_c
    # LH6 Mate
    lh617_testuak_mat_a:          erantzunak_lh6_mat_a
    lh617_testuak_mat_b:          erantzunak_lh6_mat_b
    lh617_testuak_mat_c:          erantzunak_lh6_mat_c
    # LH6 Inge
    lh617_testuak_ing_a:          erantzunak_lh6_ing_a
    lh617_testuak_ing_b:          erantzunak_lh6_ing_b
    lh617_testuak_ing_c:          erantzunak_lh6_ing_c
    # DBH4 Eusk
    dbh417_testuak_eus_a:         erantzunak_dbh4_eus_a
    dbh417_testuak_eus_b:         erantzunak_dbh4_eus_b
    dbh417_testuak_eus_c:         erantzunak_dbh4_eus_c
   # DBH4 Gazte
    dbh417_testuak_gaz_a:         erantzunak_dbh4_gaz_a
    dbh417_testuak_gaz_b:         erantzunak_dbh4_gaz_b
    dbh417_testuak_gaz_c:         erantzunak_dbh4_gaz_c
     # DBH4 Zie
    dbh417_testuak_zie_3a:        erantzunak_dbh4_zie_3a
    dbh417_testuak_zie_3b:        erantzunak_dbh4_zie_3b
    dbh417_testuak_zie_bga:       erantzunak_dbh4_zie_bga
    dbh417_testuak_zie_bgb:       erantzunak_dbh4_zie_bgb
    dbh417_testuak_zie_fqa:       erantzunak_dbh4_zie_fqa
#    dbh417_testuak_zie_fqb:       erantzunak_dbh4_zie_fqb
     # DBH4 Mate
    dbh417_testuak_mat_a:         erantzunak_dbh4_mat_a
    dbh417_testuak_mat_b:         erantzunak_dbh4_mat_b
#    dbh417_testuak_mat_c:         erantzunak_dbh4_mat_c
    # DBH4 Inge
    dbh417_testuak_ing_a:         erantzunak_dbh4_ing_a
    dbh417_testuak_ing_b:         erantzunak_dbh4_ing_b
    dbh417_testuak_ing_c:         erantzunak_dbh4_ing_c
  ed17probak:
    # Eusk
    edg051_testuak_dbh_eusa:      erantzunak_dbh_eusa
    edg051_testuak_dbh_eusbd:     erantzunak_dbh_eusbd
    edg051_testuak_lh_eusa:       erantzunak_lh_eusa
    edg051_testuak_lh_eusbd:      erantzunak_lh_eusbd
    # Gazte
    edg051_testuak_dbh_gaz:       erantzunak_dbh_gaz
    edg051_testuak_lh_gaz:        erantzunak_lh_gaz
    # Inge
    edg051_testuak_dbh_ing:       erantzunak_dbh_ing
    edg051_testuak_lh_ing:        erantzunak_lh_ing
    # Mate
    edg051_testuak_dbh_mat:       erantzunak_dbh_mat
    edg051_testuak_lh_mat:        erantzunak_lh_mat
    # Zie
    edg051_testuak_dbh_zie:       erantzunak_dbh_zie
    edg051_testuak_lh_zie:        erantzunak_lh_zie
    # G. sortak
    edg051_testuak_dbh_gsorta_a:  erantzunak_dbh_gsorta_a
    edg051_testuak_dbh_gsorta_b:  erantzunak_dbh_gsorta_b
    edg051_testuak_dbh_gsorta_c:  erantzunak_dbh_gsorta_c
    edg051_testuak_lh_gsorta_a:   erantzunak_lh_gsorta_a
    edg051_testuak_lh_gsorta_b:   erantzunak_lh_gsorta_b
    edg051_testuak_lh_gsorta_c:   erantzunak_lh_gsorta_c
    # Simul
    edg051_testuak_dbh_simul:     erantzunak_dbh_simul