pageOptions:
  p00:
    simple:
      - p00b_t04
      - p00b_t05
      - p00b_t06
      - p00b_t07
  p01:
    simple:
      - p01b_t02
      - p01b_t03
      - p01b_t04
      - p01b_t05
      - p01b_t07
      - p01b_t08
      - p01b_t09
      - p01b_t10
      - p01b_t12
      - p01b_t13
      - p01b_t14
      - p01b_t15
      - p01b_t17
      - p01b_t18
      - p01b_t19
      - p01b_t20
      - p01b_t22
      - p01b_t23
      - p01b_t24
      - p01b_t25
      - p01b_t27
      - p01b_t28
      - p01b_t29
      - p01b_t30
      - p01b_t32
      - p01b_t33
      - p01b_t34
      - p01b_t35
  p02:
    simple:
      - p02b_t02
      - p02b_t03
      - p02b_t04
      - p02b_t05
      - p02b_t07
      - p02b_t08
      - p02b_t09
      - p02b_t10
      - p02b_t12
      - p02b_t13
      - p02b_t14
      - p02b_t15
      - p02b_t17
      - p02b_t18
      - p02b_t19
      - p02b_t20
      - p02b_t22
      - p02b_t23
      - p02b_t24
      - p02b_t25
      - p02b_t27
      - p02b_t28
      - p02b_t29
      - p02b_t30
      - p02b_t32
      - p02b_t33
      - p02b_t34
      - p02b_t35
  p04:
    simple:
      - p04b_t02
      - p04b_t03
      - p04b_t04
      - p04b_t05
      - p04b_t07
      - p04b_t08
      - p04b_t09
      - p04b_t10
  p05:
    simple:
      - p05b_t02
      - p05b_t03
      - p05b_t04
      - p05b_t05
      - p05b_t07
      - p05b_t08
      - p05b_t09
      - p05b_t10
  p06:
    simple:
      - p06b_t02
      - p06b_t03
      - p06b_t04
      - p06b_t05
      - p06b_t07
      - p06b_t08
      - p06b_t09
      - p06b_t10
      - p06b_t12
      - p06b_t13
      - p06b_t14
      - p06b_t15
  p07:
    simple:
      - p07b_t02
      - p07b_t03
      - p07b_t04
      - p07b_t05
      - p07b_t07
      - p07b_t08
      - p07b_t09
      - p07b_t10
  p08:
    simple:
      - p08b_t02
      - p08b_t03
      - p08b_t04
      - p08b_t05
      - p08b_t07
      - p08b_t08
      - p08b_t09
      - p08b_t10
  p09:
    simple:
      - p09b_t02
      - p09b_t03
      - p09b_t04
      - p09b_t05
  p10:
    simple:
      - p10b_t02
      - p10b_t03
      - p10b_t04
      - p10b_t05
      - p10b_t07
      - p10b_t08
      - p10b_t09
      - p10b_t10
  p11:
    simple:
      - p11b_t02
      - p11b_t03
      - p11b_t04
      - p11b_t05
      - p11b_t07
      - p11b_t08
      - p11b_t09
      - p11b_t10
  p12:
    simple:
      - p12b_t02
      - p12b_t03
      - p12b_t04
      - p12b_t05
      - p12b_t07
      - p12b_t08
      - p12b_t09
      - p12b_t10
  p13:
    simple:
      - p13b_t02
      - p13b_t03
      - p13b_t04
      - p13b_t05
      - p13b_t07
      - p13b_t08
      - p13b_t09
      - p13b_t10
      - p13b_t12
      - p13b_t14
      - p13b_t14
      - p13b_t15
      - p14b_t02
      - p14b_t03
      - p14b_t04
      - p14b_t05
      - p14b_t07
      - p14b_t08
      - p14b_t09
      - p14b_t10

pageSideSkips:
  p14: b

pageWidths:
  p14:
    a: 100

totalPages: 14