
pageImages:
  p00:  # Page where any image's being show
    - p00b_cen_t10_t10_30_img.png
  p01:
    - p01a_izq_t01_t02_25_img.png
  p02:
    - p02a_cen_t01_t01_25_img.png
    - p02a_cen_t02_t02_75_cas.png
    - p02a_cen_t02_t02_75_eus.png
  p03:
    - p03a_cen_t02_t02_75_cas.png
    - p03a_cen_t02_t02_75_eus.png
  p04:
    - p04a_cen_t02_t02_75_cas.png
    - p04a_cen_t02_t02_75_eus.png
  p05:
    - p05a_cen_t01_t01_30_img.png
  p06:
    - p06a_cen_t02_t02_75_cas.png
    - p06a_cen_t02_t02_75_eus.png
  p07:
    - p07a_cen_t01_t01_30_img.png
    - p07a_cen_t02_t02_80_cas.png
    - p07a_cen_t02_t02_80_eus.png
    # Options' images:
    - p07b_cen_t02_t02_100_cas.png
    - p07b_cen_t02_t02_100_eus.png
    - p07b_cen_t03_t03_100_cas.png
    - p07b_cen_t03_t03_100_eus.png
    - p07b_cen_t04_t04_100_cas.png
    - p07b_cen_t04_t04_100_eus.png
    - p07b_cen_t05_t05_100_cas.png
    - p07b_cen_t05_t05_100_eus.png
  p08:
    - p08a_cen_t01_t01_25_img.png
  p09:
    - p09a_dch_t01_t02_25_img.png
    - p09b_cen_t01_t01_100_img.png
  p10:
    - p10a_dch_t01_t01_25_img.png
    - p10a_cen_t02_t02_25_img.png
    # Options' images:
    - p10b_cen_t02_t02_100_img.png
    - p10b_cen_t03_t03_100_img.png
    - p10b_cen_t04_t04_100_img.png
    - p10b_cen_t05_t05_100_img.png
  p11:
    - p11a_cen_t01_t01_25_img.png
    - p11a_cen_t02_t02_90_img.png
  p12:
    - p12a_cen_t01_t01_20_cas.png
    - p12a_cen_t01_t01_20_eus.png
  p13:
    - p13a_cen_t03_t03_20_img.png
    # Options' images:
    - p13b_cen_t02_t02_100_img.png
    - p13b_cen_t03_t03_100_img.png
    - p13b_cen_t04_t04_100_img.png
    - p13b_cen_t05_t05_100_img.png
  p14:
    - p14a_cen_t01_t01_20_cas.png
    - p14a_cen_t01_t01_20_eus.png
  p15:
    - p15a_cen_t01_t01_20_cas.png
    - p15a_cen_t01_t01_20_eus.png
    - p15a_cen_t02_t02_75_cas.png
    - p15a_cen_t02_t02_75_eus.png
  p16:
    - p16a_cen_t02_t02_33_img.png
    - p16b_cen_t01_t01_75_cas.png
    - p16b_cen_t01_t01_75_eus.png
  p17:
    - p17a_cen_t01_t01_33_img.png
  p18:
    - p18a_cen_t01_t01_33_img.png
    # Options' images:
    - p18b_cen_t02_t02_100_cas.png
    - p18b_cen_t02_t02_100_eus.png
    - p18b_cen_t03_t03_100_cas.png
    - p18b_cen_t03_t03_100_eus.png
    - p18b_cen_t04_t04_100_cas.png
    - p18b_cen_t04_t04_100_eus.png
    - p18b_cen_t05_t05_100_cas.png
    - p18b_cen_t05_t05_100_eus.png

pageTitles: # All centered texts' codes
  - p00b_t01
  - p00b_t02
  - p00b_t03
  - p01a_t01
  - p02a_t01
  - p03a_t01
  - p04a_t01
  - p05a_t01
  - p06a_t01
  - p07a_t01
  - p08a_t01
  - p09a_t01
  - p10a_t01
  - p11a_t01
  - p12a_t01
  - p13a_t01
  - p14a_t01
  - p15a_t01
  - p16a_t01
  - p17a_t01
  - p18a_t01
  - p19b_t01

pageTextReplaces:
  p00:  # Page where any replace's being done
    p00b_t06: # Items' code with "%s" in its' text(s)
      parameters: {maxLength: 10, minLength: 0, width: 20}  # Parameter(s) for the replacing template
      template:   'partial/fields/input.html.twig' # Templates' location path (TEMPLATE_FILES_DIR relative)

pageAreaWidths:
  p00:  # Page affected with any custom side-width
    b: 100  # side-letter: window-relative-width-percentage
  p09:
    a: 30
  p10:
    a: 30
  p13:
    b: 60
  p19:
    b: 100

totalPages: 19  # The final total pages