
pageImages:
  p00:
    - p00b_cen_t10_t10_90_img.png
  p01:
    - p01a_cen_t01_t01_30_img.png
  p02:
    - p02a_cen_t01_t02_30_img.png
    - p02a_cen_t01_t02_33_cas.png
    - p02a_cen_t01_t02_33_eus.png
  p03:
    - p03a_cen_t02_t02_33_cas.png
    - p03a_cen_t02_t02_33_eus.png
  p04:
    - p04a_cen_t02_t02_33_cas.png
    - p04a_cen_t02_t02_33_eus.png
    - p04b_cen_t08_t09_25_img.png
    - p04b_cen_t10_t11_25_img.png
    - p04b_cen_t12_t13_25_img.png
  p05:
    - p05a_cen_t01_t01_25_img.png
  p06:
    - p06a_cen_t02_t02_33_cas.png
    - p06a_cen_t02_t02_90_eus.png
  p07:
    - p07a_cen_t01_t01_25_img.png
    - p07a_cen_t01_t01_90_cas.png
    - p07a_cen_t01_t01_90_eus.png
    - p07b_cen_t01_t02_80_eus.png
    - p07b_cen_t01_t02_90_cas.png
    - p07b_cen_t02_t03_90_cas.png
    - p07b_cen_t02_t03_90_eus.png
    - p07b_cen_t03_t04_90_cas.png
    - p07b_cen_t03_t04_90_eus.png
    - p07b_cen_t04_t05_90_cas.png
    - p07b_cen_t04_t05_90_eus.png
  p08:
    - p08a_cen_t01_t01_25_img.png
  p09:
    - p09a_cen_t02_t02_25_img.png
  p10:
    - p10a_cen_t01_t01_20_img.png
    - p10a_cen_t02_t02_25_img.png
    - p10b_dch_t02_t03_20_img.png
    - p10b_dch_t03_t04_20_img.png
    - p10b_dch_t04_t05_20_img.png
    - p10b_dch_t05_t05_20_img.png
  p11:
    - p11a_cen_t01_t01_25_img.png
  p18:
    - p18b_dch_t02_t03_50_cas.png
    - p18b_dch_t02_t03_50_eus.png
    - p18b_dch_t04_t05_50_cas.png
    - p18b_dch_t04_t05_50_eus.png
    - p18b_izq_t01_t02_50_cas.png
    - p18b_izq_t01_t02_50_eus.png
    - p18b_izq_t03_t04_50_cas.png
    - p18b_izq_t03_t04_50_eus.png

pageReplaces:
  p00:
    p00b_t06: 'partial/board-input-field.html.twig'

pageTitles:
  - p00b_t01
  - p00b_t03
  - p01a_t01
  - p02a_t01
  - p03a_t01
  - p04a_t01
  - p05a_t01
  - p06a_t01
  - p07a_t01
  - p08a_t01
  - p09a_t01
  - p10a_t01
  - p11a_t01
  - p12a_t01
  - p13a_t01
  - p14a_t01
  - p15a_t01
  - p16a_t01
  - p17a_t01
  - p18a_t01
  - p19b_t01

pageWidths:
  p00:
    b: 100
  p19:
    b: 100

totalPages: 19