p00:
  text:
    - p00b_t05
    - p00b_t06
    - p00b_t07
    - p00b_t08
    - p00b_t09
    - p00b_t10
p01:
  text:
    - p01a_t03
    - p01a_t04
    - p01a_t05
    - p01a_t06
  simple:
    - p01b_t03
    - p01b_t04
    - p01b_t05
    - p01b_t06
    - p01b_t09
    - p01b_t10
    - p01b_t11
    - p01b_t12
p02:
  simple:
    - p02b_t02
    - p02b_t03
    - p02b_t04
    - p02b_t05
p03:
  simple:
    - p03b_t03
    - p03b_t04
    - p03b_t05
    - p03b_t06
    - p03b_t09
    - p03b_t10
    - p03b_t11
    - p03b_t12
    - p03b_t15
    - p03b_t16
    - p03b_t17
    - p03b_t18
p04:
  simple:
    - p04b_t03
    - p04b_t04
    - p04b_t05
    - p04b_t06
  libre-s:
    - p04b_t09
    - p04b_t11
    - p04b_t13
p05:
  text:
    - p05a_t03
    - p05a_t04
    - p05a_t05
    - p05a_t06
  simple:
    - p05b_t02
    - p05b_t03
    - p05b_t04
    - p05b_t05
p06:
  simple:
    - p06b_t03
    - p06b_t04
    - p06b_t05
    - p06b_t06
  libre-s:
    - p06b_t09
    - p06b_t11
    - p06b_t13
p07:
  simple:
    - p07b_t02
    - p07b_t03
    - p07b_t04
    - p07b_t05
p08:
  text:
    - p08a_t03
    - p08a_t04
    - p08a_t05
    - p08a_t06
  simple:
    - p08b_t03
    - p08b_t04
    - p08b_t05
    - p08b_t06
p09:
  simple:
    - p09b_t03
    - p09b_t04
    - p09b_t05
    - p09b_t06
p10:
  simple:
    - p10b_t02
    - p10b_t03
    - p10b_t04
    - p10b_t05
p11:
  simple:
    - p11b_t02
    - p11b_t03
    - p11b_t04
    - p11b_t05
p12:
  simple:
    - p12b_t03
    - p12b_t04
    - p12b_t05
    - p12b_t06
p13:
  simple:
    - p13b_t02
    - p13b_t03
    - p13b_t04
    - p13b_t05
p14:
  simple:
    - p14b_t02
    - p14b_t03
    - p14b_t04
    - p14b_t05
p15:
  simple:
    - p15b_t06_f1
    - p15b_t07_f1
    - p15b_t09_f2
    - p15b_t10_f2
    - p15b_t12_f3
    - p15b_t13_f3
    - p15b_t15_f4
    - p15b_t16_f4
p16:
  simple:
    - p16b_t04
    - p16b_t05
    - p16b_t06
    - p16b_t07
p17:
  simple:
    - p17b_t03
    - p17b_t04
    - p17b_t05
    - p17b_t06
    - p17b_t09
    - p17b_t10
    - p17b_t11
    - p17b_t12
p18:
  simple:
    - p18b_t02
    - p18b_t03
    - p18b_t04
    - p18b_t05