# Base dirs configuration
paths:
  # Cache's path
  cache_dir: /app/cache

  # Data files' path
  data_dir: /app/config

  # Logs files' path
  logs_dir: /app/logs

  # Public files' path
  public_dir: /public

  # Template files' path
  template_dir: /src/Resources/view

  # Translation files' path
  translations_dir: /src/Resources/translation