# Routes configuration
routes:
  - /sample
  - { path: /, methods: [GET] }
  - { path: /go!, name: boarding, methods: [POST] }
  - { path: '/{page}', action: pageRender, name: onboard, methods: [POST], requirements: { page: \d+ } }