
pageImages:
  p00:
    - p00b_cen_t06_t06_80_img.png
  p01:
    - p01a_cen_t03_t03_60_img.png
  p02:
    - p02a_cen_t01_t01_70_img.png
    - p02b_cen_t02_t02_100_cas.png
    - p02b_cen_t02_t02_100_eus.png
  p03:
    - p03a_cen_t01_t01_70_img.png
    - p03b_cen_t01_t01_100_cas.png
    - p03b_cen_t01_t01_100_eus.png
    - p03b_izq_t03_t03_100_cas.png
    - p03b_izq_t04_t04_100_cas.png
    - p03b_izq_t05_t05_100_cas.png
    - p03b_izq_t06_t06_100_cas.png
    - p03b_izq_t03_t03_100_eus.png
    - p03b_izq_t04_t04_100_eus.png
    - p03b_izq_t05_t05_100_eus.png
    - p03b_izq_t06_t06_100_eus.png
  p04:
    - p04a_cen_t01_t01_70_img.png
  p05:
    - p05a_cen_t01_t01_70_img.png
  p06:
    - p06a_cen_t01_t01_50_img.png
    - p06b_izq_t06_t06_100_img.png
    - p06b_izq_t07_t07_100_img.png
    - p06b_izq_t08_t08_100_img.png
    - p06b_izq_t09_t09_100_img.png
  p07:
    - p07a_cen_t01_t01_60_img.png
    - p07b_cen_t01_t01_90_cas.png
    - p07b_cen_t01_t01_90_eus.png
  p08:
    - p08a_cen_t01_t01_60_img.png
    - p08b_cen_t02_t02_80_cas.png
    - p08b_cen_t02_t02_80_eus.png
    - p08b_izq_t04_t04_100_img.png
    - p08b_izq_t05_t05_100_img.png
    - p08b_izq_t06_t06_100_img.png
    - p08b_izq_t07_t07_100_img.png
  p09:
    - p09a_cen_t01_t01_50_img.png
    - p09b_cen_t02_t02_25_img_A.png
    - p09b_cen_t02_t02_25_img_B.png
    - p09b_cen_t02_t02_25_img_C.png
    - p09b_dch_t02_t02_25_img_D.png    
  p10:
    - p10a_cen_t01_t01_50_img.png
    - p10b_cen_t01_t01_30_img.png
    - p10b_cen_t02_t02_25_img_A.png
    - p10b_cen_t02_t02_25_img_B.png
    - p10b_cen_t02_t02_25_img_C.png
    - p10b_cen_t02_t02_25_img_D.png
  p11:
    - p11a_cen_t02_t02_100_img.png
  p12:
    - p12a_cen_t02_t02_90_img.png
  p13:
    - p13a_cen_t02_t02_100_img.png
    - p13b_cen_t01_t01_80_cas.png
    - p13b_cen_t01_t01_80_eus.png
  p14:
    - p14a_cen_t02_t02_100_img.png
    - p14b_cen_t01_t01_90_cas.png
    - p14b_cen_t01_t01_90_eus.png
  p15:
    - p15a_cen_t02_t02_100_img.png
  p16:
    - p16a_cen_t02_t02_100_img.png
    - p16b_cen_t01_t01_90_cas.png
    - p16b_cen_t01_t01_90_eus.png
  p17:
    - p17a_cen_t02_t02_60_img.png
    - p17b_cen_t02_t02_80_cas.png
    - p17b_cen_t02_t02_80_eus.png
  p18:
    - p18a_cen_t02_t02_60_img.png
    - p18b_cen_t02_t02_70_cas.png
    - p18b_cen_t02_t02_70_eus.png
  p19:
    - p19b_cen_t01_t01_60_img.jpg
    
pageTextReplaces:
  p00:
    p00b_t02:
      parameters: {  }
      template: 'partial/fields/board-input.html.twig'
  p05:
    p05b_t09:
      parameters: {  }
      template: 'partial/fields/board-input.html.twig'
      
pageTitles:
  - p00b_t01
  - p01a_t01
  - p01a_t02
  - p02a_t01
  - p03a_t01
  - p04a_t01
  - p05a_t01
  - p06a_t01
  - p07a_t01
  - p08a_t01
  - p09a_t01
  - p10a_t01
  - p11a_t01
  - p12a_t01
  - p13a_t01
  - p14a_t01
  - p15a_t01
  - p16a_t01
  - p17a_t01
  - p18a_t01

pageAreaWidths:
  p00:
    b: 100
  p03:
    a: 40
  p04:
    a: 40
  p07:
    a: 40
  p08:
    a: 34
  p09:
    a: 30
    b: 70
  p10:
    a: 30
    b: 70
  p11:
    a: 40
    b: 60
  p12:
    a: 40
    b: 60
  p13:
    a: 30
    b: 70
  p14:
    a: 30
    b: 70
  p15:
    a: 40
    b: 60
  p16:
    a: 30
    b: 70
  p17:
    a: 40
    b: 60
  p18:
    a: 40
    b: 60
  p19:
    b: 100

totalPages: 19