
pageImages:

  p01:
    - p01a_cen_t01_t01_50_img.png
  p02:
    - p02a_cen_t02_t02_50_img.png
    - p02b_cen_t01_t01_80_eus.png
    - p02b_cen_t01_t01_80_cas.png
  p04:
    - p04a_cen_t03_t03_90_cas.png
    - p04a_cen_t03_t03_90_eus.png
  p06:
    - p06a_cen_t02_t02_80_cas.png
    - p06a_cen_t02_t02_80_eus.png
  p07:
    - p07a_cen_t03_t03_90_cas.png
    - p07a_cen_t03_t03_90_eus.png
    - p07b_cen_t01_t01_80_eus.png
    - p07b_cen_t01_t01_80_cas.png
  p09:
    - p09a_cen_t02_t02_90_cas.png
    - p09a_cen_t02_t02_90_eus.png
  p10:
    - p10a_cen_t02_t02_50_img.png
  p11:
    - p11a_cen_t02_t02_60_img.png
    - p11b_cen_t01_t01_90_cas.png
    - p11b_cen_t01_t01_90_eus.png
  p12:
    - p12a_cen_t02_t02_90_cas.png
    - p12a_cen_t02_t02_90_eus.png
  p13:
    - p13a_cen_t02_t02_90_eus.png
    - p13a_cen_t02_t02_90_cas.png
  p14:
    - p14a_cen_t01_t01_90_img.png
    - p14b_cen_t01_t01_90_eus.png
    - p14b_cen_t01_t01_90_cas.png
  p15:
    - p15a_cen_t03_t03_80_eus.png
    - p15a_cen_t03_t03_80_cas.png
  p16:
    - p16a_cen_t02_t02_70_cas.png
    - p16a_cen_t02_t02_70_eus.png
    - p16b_cen_t01_t01_50_img.png
  p17:
    - p17a_cen_t02_t02_80_cas.png
    - p17a_cen_t02_t02_80_eus.png
  p18:
    - p18b_cen_t01_t01_90_eus.png
    - p18b_cen_t01_t01_90_cas.png
  p19:
    - p19a_cen_t02_t02_50_img.png
  p20:
    - p20b_cen_t01_t01_90_cas.png
    - p20b_cen_t01_t01_90_eus.png
    - p20a_cen_t02_t02_80_eus.png
    - p20a_cen_t02_t02_80_cas.png
  p21:
    - p21b_cen_t01_t01_90_eus.png
    - p21b_cen_t01_t01_90_cas.png
  p22:
    - p22a_cen_t02_t02_100_eus.png
    - p22a_cen_t02_t02_100_cas.png
  p23:
    - p23a_cen_t01_t01_100_eus.png
    - p23a_cen_t01_t01_100_cas.png
  p24:
    - p24a_cen_t01_t01_100_cas.png
    - p24a_cen_t01_t01_100_eus.png
  p25:
    - p25a_cen_t02_t02_70_img.png
  p26:
    - p26a_cen_t02_t02_40_img.png
    - p26a_cen_t03_t03_80_img.png
  p28:
    - p28a_cen_t02_t02_80_img.png
  p29:
    - p29a_cen_t02_t02_50_eus.png
    - p29a_cen_t02_t02_50_cas.png
  p30:
    - p30a_cen_t02_t02_70_eus.png
    - p30a_cen_t02_t02_70_cas.png
    - p30b_cen_t01_t01_90_img.png
  p32:
    - p32a_cen_t02_t02_80_img.png
  p33:
    - p33a_cen_t02_t02_100_cas.png
    - p33a_cen_t02_t02_100_eus.png
  p34:
    - p34a_cen_t02_t02_90_cas.png
    - p34a_cen_t02_t02_90_eus.png
    - p34a_cen_t04_t04_90_cas.png
    - p34a_cen_t04_t04_90_eus.png
  p36:
    - p36a_cen_t02_t02_50_img.png
  p37:
    - p37a_cen_t02_t02_50_img.png
    - p37b_cen_t01_t01_100_eus.png
    - p37b_cen_t01_t01_100_cas.png
  p38:
    - p38a_cen_t02_t02_80_eus.png
    - p38a_cen_t02_t02_80_cas.png
  p39:
    - p39a_cen_t02_t02_80_img.png
  p41:
    - p41a_cen_t03_t03_100_cas.png
    - p41a_cen_t03_t03_100_eus.png

pageTitles: # All centered texts' codes
  - p00a_t01
  - p00a_t04
  - p00b_t01
  - p01a_t01
  - p02a_t01
  - p03a_t01
  - p04a_t01
  - p05a_t01
  - p06a_t01
  - p07a_t01
  - p08a_t01
  - p09a_t01
  - p10a_t01
  - p11a_t01
  - p12a_t01
  - p13a_t01
  - p14a_t01
  - p15a_t01
  - p16a_t01
  - p17a_t01
  - p18a_t01
  - p19a_t01
  - p20a_t01
  - p21a_t01
  - p22a_t01
  - p23a_t01
  - p24a_t01
  - p25a_t01
  - p26a_t01
  - p27a_t01
  - p28a_t01
  - p29a_t01
  - p30a_t01
  - p31a_t01
  - p32a_t01
  - p33a_t01
  - p34a_t01
  - p35a_t01
  - p36a_t01
  - p37a_t01
  - p38a_t01
  - p39a_t01
  - p40a_t01
  - p41a_t01
  - p42b_t01
  - p42b_t01


pageAreaWidths:
  p00:  # Page affected with any custom side-width

  p18:
    a: 40
    b: 60

  p21:
    a: 40
    b: 60

  p22:
    a: 60
    b: 40

  p23:
    a: 60
    b: 40

  p26:
    a: 40
    b: 60
  p42:
    b: 100

totalPages: 42