p00:
  text:
    - p00b_t02
    - p00b_t03
    - p00b_t04
    - p00b_t05
    - p00b_t06
    - p00b_t07
p01:
  text:

  simple:
    - p01b_t02
    - p01b_t03
    - p01b_t04
    - p01b_t05
    - p01b_t07
    - p01b_t08
    - p01b_t09
    - p01b_t10
p02:
  libre-l:
    - p02b_t03
p03:
  text:
  simple:
    - p03b_t02
    - p03b_t03
    - p03b_t04
    - p03b_t05
p04:
  text:
  simple:
    - p04b_t02
    - p04b_t03
    - p04b_t04
    - p04b_t05
p05:
  text:
  simple:
    - p05b_t02
    - p05b_t03
    - p05b_t04
    - p05b_t05
p06:
  text:
  simple:
    - p06b_t02
    - p06b_t03
    - p06b_t04
    - p06b_t05
p07:
  text:
  libre-s:
    - p07b_t05_f1
    - p07b_t07_f2
    - p07b_t09_f3
    - p07b_t11_f4
p08:
  text:
  simple:
    - p08b_t02
    - p08b_t03
    - p08b_t04
    - p08b_t05

p09:
  text:
  simple:
    - p09b_t06_f1
    - p09b_t07_f1
    - p09b_t09_f2
    - p09b_t10_f2
    - p09b_t12_f3
    - p09b_t13_f3
    - p09b_t15_f4
    - p09b_t16_f4
    - p09b_t18_f5
    - p09b_t19_f5
    - p09b_t21_f6
    - p09b_t22_f6
p10:
  text:
  simple:
    - p10b_t02
    - p10b_t03
    - p10b_t04
    - p10b_t05
p11:
  text:
  simple:
    - p11b_t03
    - p11b_t04
    - p11b_t05
    - p11b_t06

p12:
  simple:
    - p12b_t02
    - p12b_t03
    - p12b_t04
    - p12b_t05
    - p12b_t07
    - p12b_t08
    - p12b_t09
    - p12b_t10
p13:
  text:
  simple:
    - p13b_t02
    - p13b_t03
    - p13b_t04
    - p13b_t05
p14:
  text:
  simple:
    - p14b_t02
    - p14b_t03
    - p14b_t04
    - p14b_t05
p15:
  text:
  simple:
    - p15b_t06_f1
    - p15b_t07_f1
    - p15b_t09_f2
    - p15b_t10_f2
    - p15b_t12_f3
    - p15b_t13_f3
    - p15b_t15_f4
    - p15b_t16_f4
p16:
  text:
  libre-s:
    - p16b_t05_f1
    - p16b_t07_f2
    - p16b_t09_f3
    - p16b_t11_f4
    - p16b_t13_f5
    - p16b_t15_f6
    - p16b_t17_f7
    - p16b_t19_f8
p17:
  text:
  simple:
    - p17b_t02
    - p17b_t03
    - p17b_t04
    - p17b_t05
p18:
  text:
  simple:
    - p18b_t03
    - p18b_t04
    - p18b_t05
    - p18b_t06

p19:
  text:
  simple:
    - p19b_t07_f1
    - p19b_t08_f1
    - p19b_t09_f1
    - p19b_t11_f2
    - p19b_t12_f2
    - p19b_t13_f2
    - p19b_t15_f3
    - p19b_t16_f3
    - p19b_t17_f3
    - p19b_t19_f4
    - p19b_t20_f4
    - p19b_t21_f4
p20:
  text:
  simple:
    - p20b_t06_f1
    - p20b_t07_f1
    - p20b_t09_f2
    - p20b_t10_f2
    - p20b_t12_f3
    - p20b_t13_f3
    - p20b_t15_f4
    - p20b_t16_f4
    - p20b_t18_f5
    - p20b_t19_f5
    - p20b_t21_f6
    - p20b_t22_f6
p21:
  text:
  simple:
    - p21b_t02
    - p21b_t03
    - p21b_t04
    - p21b_t05
p22:
  simple:
    - p22b_t02
    - p22b_t03
    - p22b_t04
    - p22b_t05
p23:
  text:
  simple:
    - p23b_t02
    - p23b_t03
    - p23b_t04
    - p23b_t05
p24:
  text:
  simple:
    - p24b_t02
    - p24b_t03
    - p24b_t04
    - p24b_t05
p25:
  text:
  simple:
    - p25b_t02
    - p25b_t03
    - p25b_t04
    - p25b_t05
    - p25b_t07
    - p25b_t08
    - p25b_t09
    - p25b_t10
p26:
  text:
  simple:
    - p26b_t02
    - p26b_t03
    - p26b_t04
    - p26b_t05
    - p26b_t07
    - p26b_t08
    - p26b_t09
    - p26b_t10
p27:
  text:
  simple:
    - p27b_t02
    - p27b_t03
    - p27b_t04
    - p27b_t05
    - p27b_t07
    - p27b_t08
    - p27b_t09
    - p27b_t10
    - p27b_t12
    - p27b_t13
    - p27b_t14
    - p27b_t15
p28:
  text:
  simple:
    - p28b_t02
    - p28b_t03
    - p28b_t04
    - p28b_t05
p29:
  text:
  simple:
    - p29b_t02
    - p29b_t03
    - p29b_t04
    - p29b_t05
p30:
  text:
  libre-s:
    - p30b_t05_f1
    - p30b_t07_f2
    - p30b_t09_f3
    - p30b_t11_f4
    - p30b_t13_f5
    - p30b_t15_f6
p31:
  text:
  simple:
    - p31b_t02
    - p31b_t03
    - p31b_t04
    - p31b_t05
p32:
  text:
  libre-s:
    - p32b_t05_f1
    - p32b_t07_f2
    - p32b_t09_f3
    - p32b_t11_f4
p33:
  text:
  simple:
    - p33b_t02
    - p33b_t03
    - p33b_t04
    - p33b_t05
p34:
  text:
  simple:
    - p34b_t02
    - p34b_t03
    - p34b_t04
    - p34b_t05
    - p34b_t07
    - p34b_t08
    - p34b_t09
    - p34b_t10
p35:
  text:
  simple:
    - p35b_t02
    - p35b_t03
    - p35b_t04
    - p35b_t05
p36:
  text:
  simple:
    - p36b_t02
    - p36b_t03
    - p36b_t04
    - p36b_t05
p37:
  text:
  simple:
    - p37b_t02
    - p37b_t03
    - p37b_t04
    - p37b_t05
p38:
  text:
  simple:
    - p38b_t02
    - p38b_t03
    - p38b_t04
    - p38b_t05
    - p38b_t07
    - p38b_t08
    - p38b_t09
    - p38b_t10
p39:
  text:
  simple:
    - p39b_t02
    - p39b_t03
    - p39b_t04
    - p39b_t05
p40:
  text:
  simple:
    - p40b_t02
    - p40b_t03
    - p40b_t04
    - p40b_t05
p41:
  text:
  simple:
    - p41b_t02
    - p41b_t03
    - p41b_t04
    - p41b_t05
    - p41b_t07
    - p41b_t08
    - p41b_t09
    - p41b_t10