
pageImages:

  p01:
    - p01a_cen_t02_t02_80_cas.png
    - p01a_cen_t02_t02_80_eus.png
  p03:
    - p03a_cen_t02_t02_100_img.png
  p04:
    - p04a_cen_t03_t03_90_img.png
  p07:
    - p07a_cen_t03_t03_90_img.png
    - p07b_cen_t03_t03_90_cas.png
    - p07b_cen_t03_t03_90_eus.png
  p11:
    - p11a_cen_t01_t01_100_img.png
  p12:
    - p12a_cen_t02_t02_100_cas.png
    - p12a_cen_t02_t02_100_eus.png
  p13:
    - p13a_cen_t03_t03_100_img.png
    - p13b_cen_t01_t01_100_img.png
  p14:
    - p14a_cen_t02_t02_100_eus.png
    - p14a_cen_t02_t02_100_cas.png
  p15:
    - p15a_cen_t01_t01_60_img.png
  p16:
    - p16a_cen_t02_t02_70_img.png
  p18:
    - p18a_cen_t02_t02_100_eus.png
    - p18a_cen_t02_t02_100_cas.png 
    - p18a_cen_t03_t03_100_eus.png
    - p18a_cen_t03_t03_100_cas.png
  p19:
    - p19a_cen_t02_t02_100_eus.png
    - p19a_cen_t02_t02_100_cas.png
  p20:  
    - p20a_cen_t02_t02_80_img.png
    - p20b_cen_t01_t01_90_eus.png
    - p20b_cen_t01_t01_90_cas.png
    - p20b_cen_t06_t06_90_eus.png
    - p20b_cen_t06_t06_90_cas.png
  p21:
    - p21a_cen_t02_t02_100_cas.png
    - p21a_cen_t02_t02_100_eus.png
  p22:  
    - p22a_cen_t02_t02_90_img.png  
    - p22b_cen_t01_t01_100_eus.png 
    - p22b_cen_t01_t01_100_cas.png
  p23: 
    - p23a_cen_t02_t02_100_eus.png
    - p23a_cen_t02_t02_100_cas.png
  p25: 
    - p25a_cen_t01_t01_90_img.png
  p26: 
    - p26a_cen_t03_t03_80_cas.png
    - p26a_cen_t03_t03_80_eus.png
  p27: 
    - p27a_cen_t02_t02_90_cas.png
    - p27a_cen_t02_t02_90_eus.png
  p28: 
    - p28a_cen_t02_t02_100_eus.png
    - p28a_cen_t02_t02_100_cas.png
    - p28a_cen_t03_t03_90_eus.png
    - p28a_cen_t03_t03_90_cas.png
    - p28a_cen_t04_t04_100_eus.png
    - p28a_cen_t04_t04_100_cas.png
  p29: 
    - p29a_cen_t06_t06_100_eus.png
    - p29a_cen_t06_t06_100_cas.png
  p30:
    - p30a_cen_t02_t02_90_img.png
    - p30a_cen_t04_t04_90_cas.png
    - p30a_cen_t04_t04_90_eus.png
    - p30b_cen_t01_t01_60_img.jpg
  p31:
    - p31a_cen_t02_t02_80_img.png
  p32:
    - p32a_cen_t02_t02_100_img.png
  p33:
    - p33a_cen_t02_t02_60_img.png
    - p33b_cen_t06_t06_100_eus.png
    - p33b_cen_t06_t06_100_cas.png
  p34:
    - p34a_cen_t02_t02_100_img.png
  p35:
    - p35a_cen_t02_t02_100_cas.png
    - p35a_cen_t02_t02_100_eus.png
  p36:
    - p36a_cen_t02_t02_80_img.png
    - p36a_cen_t04_t04_100_eus.png
    - p36a_cen_t04_t04_100_cas.png
  p37:
    - p37a_cen_t02_t02_90_img.png
  p38:
    - p38a_cen_t03_t03_100_eus.png
    - p38a_cen_t03_t03_100_cas.png
  p39:
    - p39a_cen_t03_t03_100_eus.png
    - p39a_cen_t03_t03_100_cas.png
    
pageTitles: # All centered texts' codes
  - p00a_t01
  - p00a_t04 
  - p00b_t01
  - p01a_t01
  - p02a_t01
  - p03a_t01
  - p04a_t01
  - p05a_t01
  - p06a_t01
  - p07a_t01
  - p08a_t01
  - p09a_t01
  - p10a_t01
  - p11a_t01
  - p12a_t01
  - p13a_t01
  - p14a_t01
  - p15a_t01
  - p16a_t01
  - p17a_t01
  - p18a_t01
  - p19a_t01
  - p20a_t01
  - p21a_t01 
  - p22a_t01
  - p23a_t01
  - p24a_t01
  - p25a_t01
  - p26a_t01
  - p27a_t01
  - p28a_t01
  - p29a_t01
  - p30a_t01
  - p31a_t01 
  - p32a_t01
  - p33a_t01
  - p34a_t01
  - p35a_t01
  - p36a_t01
  - p37a_t01
  - p38a_t01
  - p39a_t01
  - p40a_t03   
  

pageAreaWidths:
  p00:  # Page affected with any custom side-width
 
  p40:
    b: 100

totalPages: 41  