p01:
  text:
  libre-m:
    - p01b_t04_f0
    - p01b_t06_f0
    - p01b_t08_f1
    - p01b_t10_f1
    - p01b_t12_f2
    - p01b_t14_f2
    - p01b_t16_f3
    - p01b_t18_f3
    - p01b_t20_f4
    - p01b_t22_f4
p02:
  text:
  libre-m:
    - p02b_t03_f0
    - p02b_t05_f0
    - p02b_t08_f1
    - p02b_t10_f1
    - p02b_t13_f2
    - p02b_t15_f2
    - p02b_t18_f3
    - p02b_t20_f3
    - p02b_t23_f4
    - p02b_t25_f4
p03:
  libre-m:
    - p03b_t03_f0
    - p03b_t05_f0
    - p03b_t08_f1
    - p03b_t10_f1
    - p03b_t13_f2
    - p03b_t15_f2
    - p03b_t18_f3
    - p03b_t20_f3
    - p03b_t23_f4
    - p03b_t25_f4
p04:
  libre-m:
    - p04b_t03_f0
    - p04b_t05_f0
    - p04b_t08_f1
    - p04b_t10_f1
    - p04b_t13_f2
    - p04b_t15_f2
    - p04b_t18_f3
    - p04b_t20_f3
    - p04b_t23_f4
    - p04b_t25_f4
p05:
  libre-m:
    - p05b_t03_f0
    - p05b_t05_f0
    - p05b_t08_f1
    - p05b_t10_f1
    - p05b_t13_f2
    - p05b_t15_f2
    - p05b_t18_f3
    - p05b_t20_f3
    - p05b_t23_f4
    - p05b_t25_f4
p06:
  libre-m:
    - p06b_t03_f0
    - p06b_t05_f0
    - p06b_t08_f1
    - p06b_t10_f1
    - p06b_t13_f2
    - p06b_t15_f2
    - p06b_t18_f3
    - p06b_t20_f3
    - p06b_t23_f4
    - p06b_t25_f4
p07:
  text:
p08:
  text:
  simple:
    - p08b_t04
    - p08b_t05
    - p08b_t06
    - p08b_t07
p09:
  text:
  simple:
    - p09b_t04
    - p09b_t05
    - p09b_t06
    - p09b_t07
p10:
  text:
  simple:
    - p10b_t03
    - p10b_t04
    - p10b_t05
    - p10b_t06
p11:
  text:
    - p11b_t04
    - p11b_t05
    - p11b_t06
    - p11b_t07
  libre-m:
    - p11b_t09_f0
    - p11b_t10_f0
    - p11b_t11_f1
    - p11b_t12_f1
p12:
  text:
    - p12b_t03
    - p12b_t04
    - p12b_t05
    - p12b_t06
  simple:
    - p12b_t08
    - p12b_t09
    - p12b_t10
    - p12b_t11
p13:
  simple:
    - p13b_t04
    - p13b_t05
    - p13b_t06
    - p13b_t07
p14:
  libre-s:
    - p14b_t05
p15:
  libre-s:
    - p15b_t10_f2
    - p15b_t14_f3
    - p15b_t16_f4
    - p15b_t20_f5
p16:
  simple:
    - p16b_t04
    - p16b_t05
    - p16b_t06
    - p16b_t07
p17:
  text:
  simple:
    - p17b_t03
    - p17b_t04
    - p17b_t05
    - p17b_t06
p18:
  text:
  simple:
    - p18b_t03
    - p18b_t04
    - p18b_t05
    - p18b_t06
    - p18b_t08
    - p18b_t09
    - p18b_t10
    - p18b_t11
p19:
  text:
  simple:
    - p19b_t03
    - p19b_t04
    - p19b_t05
    - p19b_t06
p20:
  text:
  simple:
    - p20b_t03
    - p20b_t04
    - p20b_t05
    - p20b_t06
    - p20b_t09
    - p20b_t10
    - p20b_t11
    - p20b_t12
p21:
  text:
    - p21b_t02
    - p21b_t03
    - p21b_t04
  libre-s:
    - p21b_t05
  simple:
    - p21b_t08
    - p21b_t09
    - p21b_t10
    - p21b_t11
p22:
  text:
    - p22b_t02
    - p22b_t03
    - p22b_t04
  libre-s:
    - p22b_t12_f1
    - p22b_t13_f1
    - p22b_t14_f1
    - p22b_t16_f2
    - p22b_t17_f2
    - p22b_t18_f2
    - p22b_t20_f3
    - p22b_t21_f3
    - p22b_t22_f3
p23:
  simple:
    - p23b_t03
    - p23b_t04
    - p23b_t05
    - p23b_t06
p24:
  simple:
    - p24b_t03
    - p24b_t04
    - p24b_t05
    - p24b_t06
p25:
  text:
    - p25b_t02
    - p25b_t03
    - p25b_t04
  simple:
    - p25b_t10_f1
    - p25b_t11_f1
    - p25b_t13_f2
    - p25b_t14_f2
    - p25b_t16_f3
    - p25b_t17_f3
p26:
  text:
  simple:
    - p26b_t03
    - p26b_t04
    - p26b_t05
    - p26b_t06
    - p26b_t09
    - p26b_t10
    - p26b_t11
    - p26b_t12
p27:
  simple:
    - p27b_t03
    - p27b_t04
    - p27b_t05
    - p27b_t06
    - p27b_t12_f1
    - p27b_t13_f1
    - p27b_t15_f2
    - p27b_t16_f2
    - p27b_t18_f3
    - p27b_t19_f3
    - p27b_t21_f4
    - p27b_t22_f4
p28:
  text:
  simple:
    - p28b_t02
    - p28b_t03
    - p28b_t04
    - p28b_t05
    - p28b_t07
    - p28b_t08
    - p28b_t09
    - p28b_t10
p29:
  text:
  simple:
    - p29b_t03
    - p29b_t04
    - p29b_t05
    - p29b_t06
    - p29b_t09
    - p29b_t10
    - p29b_t11
    - p29b_t12
p30:
  text:
  simple:
    - p30b_t04
    - p30b_t05
    - p30b_t06
    - p30b_t07
p31:
  text:
  simple:
    - p31b_t03
    - p31b_t04
    - p31b_t05
    - p31b_t06
    - p31b_t09
    - p31b_t10
    - p31b_t11
    - p31b_t12
p32:
  libre-s:
    - p32b_t03
  simple:
    - p32b_t06
    - p32b_t07
    - p32b_t08
    - p32b_t09
p33:
  simple:
    - p33b_t07_f1
    - p33b_t08_f1
    - p33b_t10_f2
    - p33b_t11_f2
    - p33b_t13_f3
    - p33b_t14_f3
    - p33b_t16_f4
    - p33b_t17_f4
