
pageImages:
  p00:
    - p00b_cen_t06_t06_40_img.png
  p01:
    - p01a_cen_t03_t03_40_img.png
  p02:
    - p02a_cen_t02_t02_30_img.png
  p03:
    - p03a_cen_t02_t02_60_img.png
    - p03a_cen_t03_t03_70_img.png
  p04:
    - p04b_cen_t02_t02_40_img.png
  p05:
    - p05a_cen_t02_t02_90_img.png
    - p05a_dch_t04_t05_40_img.png
  p06:
    - P06a_izq_t01_t01_10_img.png
    - p06a_izq_t06_t07_40_img.png
  p07:
    - P07a_izq_t01_t01_10_img.png
    - p07a_cen_t03_t03_100_img.png
  p08:
    - p08b_cen_t01_t01_60_img.jpg

pageAudios:
  p01:
    - p01a_cen_t06_t06_x2_eus.ogg
    - p01a_cen_t06_t06_x2_eus.mp3
  p02:
    - p02a_cen_t05_t05_x2_eus.ogg
    - p02a_cen_t05_t05_x2_eus.mp3
  p03:
    - p03a_cen_t06_t06_x2_eus.ogg
    - p03a_cen_t06_t06_x2_eus.mp3

pageTitles:
  - p00b_t01
  - p01a_t01
  - p01a_t03
  - p01a_t06
  - p01b_t00
  - p02a_t01
  - p02a_t05
  - p03a_t01
  - p03a_t06
  - p04b_t01
  - p05a_t02
  - p05b_t00
  - p06a_t02
  - p06b_t00
  - p07a_t02
  - p07b_t00
  - p08b_t03

pageAreaWidths:
  p00:
    b: 100
  p04:
    b: 100
  p07:
    b: 35
  p08:
    b: 100

totalPages: 8