
pageImages:
  p00:  # Page where any image's being show
    - p00a_cen_t19_t19_20_img.png
    - p00a_izq_t14_t15_30_img.png
  p01:
    - p01a_cen_t01_t01_90_img.png
    - p01a_cen_t05_t05_20_img.png
    - p01a2_cen_t01_t01_90_img.png
    - p01a2_cen_t05_t05_20_img.png
    - p01b_cen_t16_t16_20_img_A.png
    - p01b_cen_t16_t16_20_img_B.png
    - p01b_cen_t16_t16_20_img_C.png
    - p01b_cen_t16_t16_20_img_D.png
    - p01b_cen_t22_t22_90_img_A.png
    - p01b_cen_t22_t22_90_img_B.png
    - p01b_cen_t22_t22_90_img_C.png
    - p01b_cen_t22_t22_90_img_D.png
  p02:
    - p02a_cen_t01_t01_60_img.png
    - p02a_cen_t05_t05_20_img.png
    - p02a2_cen_t01_t01_60_img.png
    - p02a2_cen_t05_t05_20_img.png
    - p02b_cen_t06_t06_40_img_A.png
    - p02b_cen_t06_t06_40_img_B.png
    - p02b_cen_t06_t06_40_img_C.png
    - p02b_cen_t06_t06_40_img_D.png
    - p02b_cen_t18_t18_25_img_A.png
    - p02b_cen_t18_t18_25_img_B.png
    - p02b_cen_t18_t18_25_img_C.png
    - p02b_cen_t18_t18_25_img_D.png
  p03:
    - p03a_cen_t05_t05_20_img.png
    - p03a_cen_t05_t05_60_img_A.png
    - p03a_cen_t05_t05_60_img_B.png
    - p03a_cen_t05_t05_60_img_C.png
    - p03a_cen_t05_t05_60_img_D.png
    - p03a_cen_t05_t05_60_img_E.png
    - p03a_cen_t05_t05_60_img_F.png
    - p03a2_cen_t05_t05_20_img.png
    - p03a2_cen_t05_t05_60_img_A.png
    - p03a2_cen_t05_t05_60_img_B.png
    - p03a2_cen_t05_t05_60_img_C.png
    - p03a2_cen_t05_t05_60_img_D.png
    - p03a2_cen_t05_t05_60_img_E.png
    . p03a2_cen_t05_t05_60_img_F.png
  p04:
    - p04a_cen_t01_t01_80_img.png
    - p04a_cen_t04_t04_20_img.png
    - p04a2_cen_t01_t01_80_img.png
    - p04a2_cen_t04_t04_20_img.png
    - p04b_cen_t06_t06_40_img_A.png
    - p04b_cen_t06_t06_40_img_B.png
    - p04b_cen_t06_t06_40_img_C.png
    - p04b_cen_t06_t06_40_img_D.png
    - p04b_cen_t07_t07_40_img_A.png
    - p04b_cen_t07_t07_40_img_B.png
    - p04b_cen_t07_t07_40_img_C.png
    - p04b_cen_t07_t07_40_img_D.png    
  p05:
    - p05b_cen_t01_t01_50_img.png
  p06:
    - p06a_cen_t03_t03_80_img.png
    - p06b_cen_t01_t01_40_img_A.png
    - p06b_cen_t01_t01_40_img_B.png
    - p06b_cen_t01_t01_40_img_C.png
    - p06b_cen_t01_t01_40_img_D.png
    - p06b_cen_t07_t07_40_img_A.png
    - p06b_cen_t07_t07_40_img_B.png
    - p06b_cen_t07_t07_40_img_C.png
    - p06b_cen_t07_t07_40_img_D.png
    - p06b_cen_t12_t12_40_img_A.png
    - p06b_cen_t12_t12_40_img_B.png
    - p06b_cen_t12_t12_40_img_C.png
    - p06b_cen_t12_t12_40_img_D.png 
  p07:
    - p07a_cen_t03_t03_40_img_B.png
    - p07a_cen_t03_t03_60_img_A.png
  p08:
    - p08a_dch_t13_t13_25_img.png
    - p08a_izq_t04_t05_25_img.png
    - p08a_izq_t06_t07_25_img.png
    - p08a_izq_t09_t12_25_img.png
  p09:
    - p09a_cen_t02_t02_80_img.png
  p10:
    - p10a_cen_t03_t03_90_img.png

pageTitles: # All centered texts' codes
  - p00b_t01
  - p00a_t02
  - p00a_t13
  - p01a_t01
  - p01a_t06
  - p01a2_t01
  - p01a2_t06
  - p02a_t01
  - p02a_t06
  - p02a2_t01
  - p02a2_t06
  - p03a_t01
  - p03a_t06
  - p03a2_t01
  - p03a2_t06
  - p04a_t01
  - p04a_t06
  - p04a2_t01
  - p04a2_t06
  - p05a_t01
  - p06a_t02
  - p07a_t02
  - p08a_t02
  - p09a_t02
  - p10a_t02
  - p11a_t01
  
pageTextReplaces:
  
pageAreaWidths:
  p05:  # Page affected with any custom side-width
    a: 100  # side-letter: window-relative-width-percentage
  p11:
    b: 100

# TODO: being dynamic
totalPages: 11  # The final total pages