
pageImages:
  p00:  # Page where any image's being show
    - p00b_izq_t05_t06_30_img.png
  p01:
    - p01a_cen_t01_t01_90_img.png
    - p01b_cen_t17_t17_20_img.png
    - p01b_cen_t18_t18_20_img.png
    - p01b_cen_t19_t19_20_img.png
    - p01b_cen_t20_t20_20_img.png
    - p01b_cen_t27_t27_90_img.png
    - p01b_cen_t28_t28_90_img.png
    - p01b_cen_t29_t29_90_img.png
    - p01b_cen_t30_t30_90_img.png
  p02:
    - p02a_cen_t01_t01_60_img.png
    - p02b_cen_t07_t07_40_img.png
    - p02b_cen_t08_t08_40_img.png
    - p02b_cen_t09_t09_40_img.png
    - p02b_cen_t10_t10_40_img.png
    - p02b_cen_t23_t23_25_img.png
    - p02b_cen_t24_t24_25_img.png
    - p02b_cen_t25_t25_25_img.png
    - p02b_cen_t26_t26_25_img.png
  p03:
    - p03a_cen_t07_t07_60_img.png
    - p03a_cen_t08_t08_60_img.png
    - p03a_cen_t09_t09_60_img.png
    - p03a_cen_t10_t10_60_img.png
    - p03a_cen_t11_t11_60_img.png
    - p03a_cen_t12_t12_60_img.png
  p04:
    - p04a_cen_t01_t01_80_img.png
    - p04b_cen_t07_t07_40_img.png
    - p04b_cen_t08_t08_40_img.png
    - p04b_cen_t09_t09_40_img.png
    - p04b_cen_t10_t10_40_img.png
    - p04b_cen_t12_t12_40_img.png
    - p04b_cen_t13_t13_40_img.png
    - p04b_cen_t14_t14_40_img.png
    - p04b_cen_t15_t15_40_img.png    
  p05:
    - p05b_cen_t01_t01_50_img.png
  p06:
    - p06a_cen_t03_t03_80_img.png
    - p06b_cen_t02_t02_40_img.png
    - p06b_cen_t03_t03_40_img.png
    - p06b_cen_t04_t04_40_img.png
    - p06b_cen_t05_t05_40_img.png
    - p06b_cen_t12_t12_40_img.png
    - p06b_cen_t13_t13_40_img.png
    - p06b_cen_t14_t14_40_img.png
    - p06b_cen_t15_t15_40_img.png
    - p06b_cen_t17_t17_40_img.png
    - p06b_cen_t18_t18_40_img.png
    - p06b_cen_t19_t19_40_img.png
    - p06b_cen_t20_t20_40_img.png 
  p07:
    - p07a_cen_t03_t03_40_img_B.png
    - p07a_cen_t03_t03_60_img_A.png
  p08:
    - p08a_dch_t13_t13_25_img.png
    - p08a_izq_t04_t05_25_img.png
    - p08a_izq_t06_t07_25_img.png
    - p08a_izq_t09_t12_25_img.png
  p09:
    - p09a_cen_t02_t02_80_img.png
  p10:
    - p10a_cen_t03_t03_90_img.png

pageTitles: # All centered texts' codes
  - p00b_t01
  - p00b_t02
  - p00b_t04
  - p01a_t01
  - p01a_t06
  - p02a_t01
  - p02a_t06
  - p03a_t01
  - p03a_t06
  - p04a_t01
  - p04a_t06
  - p05a_t01
  - p06a_t02
  - p07a_t02
  - p08a_t02
  - p09a_t02
  - p10a_t02
  - p11a_t01
  
pageTextReplaces:

pageAudios:
  p01:
    - p01a_cen_t06_t06_x3_cas.mp3
    - p01a_cen_t06_t06_x3_eus.mp3
    - p02a_cen_t06_t06_x3_cas.mp3
    - p02a_cen_t06_t06_x3_eus.mp3
    - p03a_cen_t06_t06_x3_cas.mp3
    - p03a_cen_t06_t06_x3_eus.mp3
    - p04a_cen_t06_t06_x3_cas.mp3
    - p04a_cen_t06_t06_x3_eus.mp3
  
pageAreaWidths:
 p00:
    b: 100
 p05:  # Page affected with any custom side-width
    b: 100  # side-letter: window-relative-width-percentage
 p11:
    b: 100

# TODO: being dynamic
totalPages: 11  # The final total pages