
pageImages:
  p00:
    - p00b_cen_t02_t02_50_img.png
  p01:
    - p01a_cen_t02_t02_90_cas.png
    - p01a_cen_t02_t02_90_eus.png
  p02:
    - p02a_cen_t02_t02_90_cas.png
    - p02a_cen_t02_t02_90_eus.png
  p03:
    - p03a_dch_t02_t02_20_img.png
    - p03a_cen_t03_t03_90_cas.png
    - p03a_cen_t03_t03_90_eus.png
  p04:
    - p04a_izq_t02_t02_30_img.png
    - p04a_cen_t03_t03_90_cas.png
    - p04a_cen_t03_t03_90_eus.png
  p05:
    - p05a_izq_t02_t02_30_img.png
    - p05a_cen_t03_t03_90_cas.png
    - p05a_cen_t03_t03_90_eus.png
  p06:
    - p06a_cen_t02_t02_30_img.png
  p07:
    - p13a_cen_t02_t02_60_img.png
    - p13a_izq_t03_t03_40_img.png
    - p13b_cen_t02_t02_50_img.png
  p14:
    - p14a_cen_t02_t02_60_img.png
    - p14a_izq_t03_t03_40_img.png
    - p14b_cen_t01_t01_30_eus.png
    - p14b_cen_t01_t01_30_cas.png
    - p14b_cen_t02_t02_95_eus.png
    - p14b_cen_t02_t02_95_cas.png
  p15:
    - p15a_cen_t02_t02_80_img.png
    - p15a_izq_t03_t03_40_img.png
    - p15b_cen_t01_t01_30_img.png
  p16:
    - p16a_cen_t02_t02_80_img.png
    - p16a_izq_t03_t03_40_img.png
    - p16b_cen_t01_t01_80_img.png
  p17:
    - p17a_izq_t03_t03_40_img.png
    - p17a_cen_t02_t02_80_img.png
    - p17b_cen_t01_t01_50_img.png


pageTitles:
  - p00b_t01
  - p01b_t01
  - p07b_t01
  - p08a_t01
  - p09a_t01
  - p10a_t01
  - p11a_t01
  - p12a_t01
  - p13a_t01
  - p14a_t01
  - p15a_t01
  - p16a_t01
  - p17a_t01
 

pageAreaWidths:
  p00:
    b: 100
  p17:
    b: 100


totalPages: 17