
pageAudios:
  p01:
    - p01a_cen_t07_t07_x3_cas.mp3
 #   - p01a_cen_t07_t07_x3_cas.ogg
  p02:
    - p02a_cen_t05_t05_x3_cas.mp3
 #   - p02a_cen_t05_t05_x3_cas.ogg
pageImages:
  p00:
    - p00a_cen_t08_t08_60_img.jpg
  p01:
    - p01a_izd_t01_t01_20_img.png
    - p01a_cen_t04_t04_80_img.jpg
  p02:
    - p02a_izd_t01_t01_20_img.png
    - p02a_cen_t02_t02_60_img.jpg
  p03:
    - p03b_cen_t02_t02_40_img.jpg
  p04:
    - p04a_izd_t01_t01_20_img.png
    - p04b_cen_t07_t07_100_img.png
    - p04b_cen_t08_t08_100_img.png
    - p04b_cen_t09_t09_100_img.png
    - p04b_cen_t10_t10_100_img.png
  p05:
    - p05a_izq_t01_t01_20_img.png
    - p05a_izq_t04_t04_50_img.png
  p06:
    - p06a_izq_t01_t01_20_img.png
    - p06a_cen_t02_t02_100_img.png
  p07:
    - p07a_izq_t01_t01_20_img.png
    - p07a_cen_t01_t01_100_img.jpg
    - p07b_cen_t16_t16_60_img.jpg
    - p07b_cen_t31_t31_30_img.png
  p08:
    - p08b_cen_t01_t01_60_img.jpg

pageTitles:
  - p00a_t01
  - p00a_t02
  - p01a_t01
  - p01a_t03
  - p01a_t07
  - p02a_t01
  - p02a_t05
  - p03a_t01
  - p04a_t02
  - p05a_t02
  - p06a_t02
  - p08b_t03

pageAreaWidths:
  p03:
    b: 100
  p04:
    a: 30
    b: 70
  p06:
    a: 60
    b: 40
  p08:
    b: 100
totalPages: 8