
imports:
  - { resource: framework.yml }
  - { resource: twig.yml }

#doctrine:
#    dbal:
#        driver:   %database_driver%
#        host:     %database_host%
#        port:     %database_port%
#        dbname:   %database_name%
#        user:     %database_user%
#        password: %database_password%
#        charset:  UTF8

#dunglas_action: