
imports:
  - { resource: framework.yml }
  - { resource: twig.yml }

#doctrine:
#    dbal:
#        driver:   %driver%
#        host:     %host%
#        port:     %port%
#        dbname:   %dbname%
#        user:     %user%
#        password: %password%
#        charset:  UTF8

#dunglas_action: