framework:
    secret:               %secret%
    http_method_override: true
    trusted_proxies:      []
    ide:                  'phpstorm://open?file=%%f&line=%%l'
    test:                 ~
    default_locale:       %locale%
    trusted_hosts:        %trusted_hosts%

    # form configuration
    form:
        enabled:              false
        csrf_protection:
            enabled:          true
            field_name:       ~

    # esi configuration
    esi:
        enabled:              false

    # fragments configuration
    fragments:
        enabled:              false
        path:                 /_fragment

    # profiler configuration
    profiler:
        enabled:              %kernel.debug%
        collect:              true
        only_exceptions:      false
        only_master_requests: false
        dsn:                  file:%kernel.cache_dir%/profiler
        matcher:
#            ip:                   ~
            # use the urldecoded format
            path:                 ~ # Example: ^/path to resource/
            service:              ~

    # router configuration
#    router:
#        resource:             ~ # Required
#        type:                 ~
#        http_port:            80
#        https_port:           443

        # * set to true to throw an exception when a parameter does not
        #   match the requirements
        # * set to false to disable exceptions when a parameter does not
        #   match the requirements (and return null instead)
        # * set to null to disable parameter checks against requirements
        #
        # 'true' is the preferred configuration in development mode, while
        # 'false' or 'null' might be preferred in production
#        strict_requirements:  true

    # session configuration
    session:
        storage_id:           session.storage.native
        handler_id:           session.handler.native_file
        name:                 ~
        cookie_lifetime:      ~
        cookie_path:          ~
        cookie_domain:        ~
        cookie_secure:        ~
        cookie_httponly:      ~
        gc_divisor:           ~
        gc_probability:       ~
        gc_maxlifetime:       ~
        save_path:            '%kernel.cache_dir%/sessions'

    # serializer configuration
    serializer:
       enabled: false

    # assets configuration
#    assets:
#        base_path:          ~
#        base_urls:          []
#        version:            ~
#        version_format:     '%%s?%%s'
#        packages:
            # Prototype
#            name:
#                base_path:            ~
#                base_urls:            []
#                version:              ~
#                version_format:       '%%s?%%s'

    # templating configuration
#    templating:
#        hinclude_default_template:  ~
#        form:
#            resources:
                # Default:
#                - FrameworkBundle:Form
#        cache:                ~
#        engines:              [php, twig] # Required
#        loaders:              []

    # translator configuration
    translator:
        enabled:              false
        fallbacks:            [en]
        logging:              %kernel.debug%
        paths:                []

    # validation configuration
    validation:
        enabled:              false
        cache:                ~
        enable_annotations:   false
        translation_domain:   validators

    # annotation configuration
    annotations:
        cache:                file
        file_cache_dir:       %kernel.cache_dir%/annotations
        debug:                %kernel.debug%

    # PHP errors handling configuration
#    php_errors:
#        log:                  false
#        throw:                %kernel.debug%