twig:
    exception_controller:  twig.controller.exception:showAction
#    form_themes:
        # Default:
#        - form_div_layout.html.twig
        # Bootstrap:
#        - bootstrap_3_layout.html.twig
#        - bootstrap_3_horizontal_layout.html.twig
        # Foundation
#        - foundation_5_layout.html.twig
        # Example:
#        - MyBundle::form.html.twig
#    globals:
        # Examples:
#        foo:                 '@bar'
#        pi:                  3.14
        # Example options, but the easiest use is as seen above
#        some_variable_name:
            # a service id that should be the value
#            id:                ~
            # set to service or leave blank
#            type:              ~
#            value:             ~
    autoescape:                false
    # See http://twig.sensiolabs.org/doc/recipes.html#using-the-template-name-to-set-the-default-escaping-strategy
    autoescape_service:        ~ # Example: '@my_service'
    autoescape_service_method: ~ # use in combination with autoescape_service option
#    base_template_class:       ~ # Example: Twig_Template
#    cache:                     %kernel.cache_dir%/twig
    cache:                     %kernel.cache_dir%/twig
    charset:                   %kernel.charset%
    debug:                     %kernel.debug%
    strict_variables:          true
#    auto_reload:               ~
#    optimizations:             ~
    paths:
        '%kernel.root_dir%/Resources/view': App
        '%kernel.root_dir%/../vendor/symfony/web-profiler-bundle/Resources/views': WebProfiler
        '%kernel.root_dir%/../vendor/elao/web-profiler-extra-bundle/Resources/views': WebProfilerExtra