
pageAudios:
  p01:
    - p01a_cen_t08_t08_x3_eus.ogg
  p02:
    - p02a_cen_t03_t03_x3_eus.ogg
  p03:
    - p03a_cen_t03_t03_x3_eus.ogg

pageImages:
  p01:
    - p01a_cen_t07_t07_70_img.png
    - p01a_cen_t08_t08_30_img.jpg
  p02:
    - p02a_cen_t02_t02_50_img.png
    - p02a_cen_t03_t03_30_img.jpg
  p03:
    - p03a_cen_t02_t02_50_img.jpg
  p04:
    - p04a_dch_t06_t06_20_img.png
  p05:
    - p05a_dch_t02_t02_20_img.png
  p06:
    - p06a_cen_t01_t01_100_img.png
  p07:
    - p07a_cen_t01_t01_100_img.png
  p08:
    - p08a_cen_t01_t01_100_img.png
  p09:
    - p09a_izq_t04_t04_30_img.png
  p10:
    - p10a_izq_t04_t04_30_img.png
  p11:
    - p11a_cen_t02_t02_100_img.png
  p12:
    - p12a_cen_t02_t02_100_img.png
  p13:
    - p13b_cen_t01_t01_60_img.jpg

pageTitles:
  - p00a_t01
  - p00a_t02
  - p00b_t01
  - p01a_t01
  - p01a_t06
  - p02a_t01
  - p03a_t01
  - p04a_t01
  - p04a_t06
  - p05a_t02
  - p06a_t00
  - p07a_t00
  - p08a_t00
  - p09a_t00
  - p09a_t02
  - p10a_t00
  - p10a_t02
  - p11a_t00
  - p11a_t02
  - p12a_t00
  - p12a_t02
  - p13b_t01

pageAreaWidths:
   p06:
    a: 60
    b: 40
   p11:
    a: 60
    b: 40
   p12:
    a: 60
    b: 40
   p13:
    b: 100

totalPages: 13