
pageImages:
  p01:
    - p01a_cen_t02_t02_80_img.png
  p02:
    - p02a_cen_t02_t02_90_cas.png
    - p02a_cen_t02_t02_90_eus.png
  p03:
    - p03a_cen_t03_t03_80_img.png
  p04:
    - p04b_cen_t01_t01_100_eus.png
    - p04b_cen_t01_t01_100_cas.png
  p05:
    - p05a_cen_t02_t02_80_eus.png
    - p05a_cen_t02_t02_80_cas.png
  p06:
    - p06a_cen_t02_t02_80_eus.png
    - p06a_cen_t02_t02_80_cas.png
    - p06b_cen_t07_t07_80_eus.png
    - p06b_cen_t07_t07_80_cas.png
  p07:
    - p07b_cen_t01_t01_80_eus.png
    - p07b_cen_t01_t01_80_cas.png
  p08:
    - p08a_cen_t03_t03_80_img.jpg
  p09:
    - p09a_cen_t02_t02_70_img.png
  p10:
    - p10a_cen_t02_t02_80_eus.png
    - p10a_cen_t02_t02_80_cas.png
  p11:
    - p11a_cen_t02_t02_70_img.png
    - p11b_cen_t01_t01_80_img.png
  p12:
    - p12b_cen_t01_t01_80_img.png
  p13:
    - p13a_cen_t02_t02_70_img.png
  p14:
    - p14a_cen_t02_t02_80_img.jpg
    - p14a_cen_t03_t03_80_cas.png
    - p14a_cen_t03_t03_80_eus.png
  p15:
    - p15a_cen_t02_t02_80_eus.png
    - p15a_cen_t02_t02_80_cas.png
  p16:
    - p16a_cen_t02_t02_60_img.jpg
  p17:
    - p17a_cen_t02_t02_80_cas.png
    - p17a_cen_t02_t02_80_eus.png
  p18:
    - p18a_cen_t02_t02_90_img.png
    - p18a_cen_t03_t03_60_cas.png
    - p18a_cen_t03_t03_60_eus.png
  p19:
    - p19a_cen_t02_t02_100_eus.png
    - p19a_cen_t02_t02_100_cas.png
  p20:
    - p20a_cen_t02_t02_60_img.png
    - p20a_cen_t03_t03_60_eus.png
    - p20a_cen_t03_t03_60_cas.png
    - p20a_cen_t04_t04_60_eus.png
    - p20a_cen_t04_t04_60_cas.png
  p21:
    - p21a_cen_t03_t03_90_img.jpg
    - p21b_cen_t07_t07_30_eus.png
    - p21b_cen_t07_t07_30_cas.png
    - p21b_cen_t08_t08_100_eus.png
    - p21b_cen_t08_t08_100_cas.png
  p22:
    - p22a_cen_t01_t01_80_img.png
  p23:
    - p23a_cen_t02_t02_90_cas.png
    - p23a_cen_t02_t02_90_eus.png
  p24:
    - p24a_cen_t02_t02_80_img.png
    - p24b_cen_t06_t06_90_eus.png
    - p24b_cen_t06_t06_90_cas.png
    - p24b_cen_t12_t12_90_eus.png
    - p24b_cen_t12_t12_90_cas.png
  p25:
    - p25a_cen_t02_t02_80_img.png
    - p25b_cen_t01_t01_80_img.png
    - p25b_cen_t07_t07_90_eus.png
    - p25b_cen_t07_t07_90_cas.png
    - p25b_cen_t08_t08_80_eus.png
    - p25b_cen_t08_t08_80_cas.png
  p26:
    - p26b_cen_t02_t02_60_img.png
    - p26b_cen_t08_t08_90_eus.png
    - p26b_cen_t08_t08_90_cas.png
  p27:
    - p27a_cen_t02_t02_80_eus.png
    - p27a_cen_t02_t02_80_cas.png
  p28:
    - p28a_cen_t02_t02_60_img.png
    - p28a_cen_t04_t04_90_cas.png
    - p28a_cen_t04_t04_90_eus.png
    - p28b_cen_t06_t06_70_img.png
  p29:
    - p29a_cen_t03_t03_50_img.png
    - p29b_cen_t01_t01_90_eus.png
    - p29b_cen_t01_t01_90_cas.png
  p33:
    - p33a_cen_t02_t02_100_img.png
  p34:
    - p34a_cen_t02_t02_100_eus.png
    - p34a_cen_t02_t02_100_cas.png
pageTitles: # All centered texts' codes
  - p00a_t01
  - p00a_t04
  - p00b_t01
  - p01a_t01
  - p02a_t01
  - p03a_t01
  - p04a_t01
  - p05a_t01
  - p06a_t01
  - p07a_t01
  - p08a_t01
  - p09a_t01
  - p10a_t01
  - p11a_t01
  - p12a_t01
  - p13a_t01
  - p14a_t01
  - p15a_t01
  - p16a_t01
  - p17a_t01
  - p18a_t01
  - p19a_t01
  - p20a_t01
  - p21a_t01
  - p22a_t01
  - p23a_t01
  - p24a_t01
  - p25a_t01
  - p26a_t01
  - p27a_t01
  - p28a_t01
  - p29a_t01
  - p30a_t01
  - p31a_t01
  - p32a_t01
  - p33a_t01
  - p34a_t01
  - p35b_t01
  - p35b_t02
pageAreaWidths:
  p42:
    b: 100
totalPages: 35