p00:
  text:
    - p00b_t02
    - p00b_t03
    - p00b_t04
    - p00b_t05
    - p00b_t06
    - p00b_t07
p01:
  text:
  simple:
    - p01b_t06_f1
    - p01b_t07_f1
    - p01b_t09_f2
    - p01b_t10_f2
    - p01b_t12_f3
    - p01b_t13_f3
    - p01b_t15_f4
    - p01b_t16_f4
    - p01b_t18_f5
    - p01b_t19_f5
p02:
  simple:
    - p02b_t06_f1
    - p02b_t07_f1
    - p02b_t09_f2
    - p02b_t10_f2
    - p02b_t12_f3
    - p02b_t13_f3
    - p02b_t15_f4
    - p02b_t16_f4
p03:
  text:
  simple:
    - p03b_t07_f1
    - p03b_t08_f1
    - p03b_t09_f1
    - p03b_t11_f2
    - p03b_t12_f2
    - p03b_t13_f2
    - p03b_t15_f3
    - p03b_t16_f3
    - p03b_t17_f3
    - p03b_t19_f4
    - p03b_t20_f4
    - p03b_t21_f4
    - p03b_t23
    - p03b_t24
    - p03b_t25
    - p03b_t26
p04:
  text:
  simple:
    - p04b_t02
    - p04b_t03
    - p04b_t04
    - p04b_t05
p05:
  text:
  simple:
    - p05b_t02
    - p05b_t03
    - p05b_t04
    - p05b_t05
p06:
  text:
  simple:
    - p06b_t02
    - p06b_t03
    - p06b_t04
    - p06b_t05
    - p06b_t09
    - p06b_t10
    - p06b_t11
    - p06b_t12
p07:
  text:
  simple:
    - p07b_t02
    - p07b_t03
    - p07b_t04
    - p07b_t05
p08:
  text:
  simple:
    - p08b_t06_f1
    - p08b_t07_f1
    - p08b_t09_f2
    - p08b_t10_f2
    - p08b_t12_f3
    - p08b_t13_f3
    - p08b_t15_f4
    - p08b_t16_f4
    - p08b_t18_f5
    - p08b_t19_f5

p09:
  text:
  simple:
    - p09b_t02
    - p09b_t03
    - p09b_t04
    - p09b_t05
p10:
  text:
  simple:
    - p10b_t02
    - p10b_t03
    - p10b_t04
    - p10b_t05
p11:
  text:
  simple:
    - p11b_t03
    - p11b_t04
    - p11b_t05
    - p11b_t06
    - p11b_t08
    - p11b_t09
    - p11b_t10
    - p11b_t11

p12:
  simple:
    - p12b_t02
    - p12b_t03
    - p12b_t04
    - p12b_t05
p13:
  text:
  simple:
    - p13b_t02
    - p13b_t03
    - p13b_t04
    - p13b_t05
p14:
  text:
  simple:
    - p14b_t02
    - p14b_t03
    - p14b_t04
    - p14b_t05
p15:
  text:
  simple:
    - p15b_t02
    - p15b_t03
    - p15b_t04
    - p15b_t05
p16:
  text:
  libre-l:
    - p16b_t02
    - p16b_t03
    - p16b_t04
p17:
  text:
  simple:
    - p17b_t02
    - p17b_t03
    - p17b_t04
    - p17b_t05
p18:
  text:
  simple:
    - p18b_t02
    - p18b_t03
    - p18b_t04
    - p18b_t05

p19:
  text:
  simple:
    - p19b_t02
    - p19b_t03
    - p19b_t04
    - p19b_t05
p20:
  text:
  simple:
    - p20b_t06_f1
    - p20b_t07_f1
    - p20b_t09_f2
    - p20b_t10_f2
    - p20b_t12_f3
    - p20b_t13_f3
    - p20b_t15_f4
    - p20b_t16_f4
    - p20b_t18
    - p20b_t19
    - p20b_t20
    - p20b_t21
p21:
  text:
  libre-s:   
    - p21b_t12_f1
    - p21b_t14_f2
    - p21b_t16_f3
    - p21b_t18_f4
    - p21b_t20_f5
    - p21b_t22_f6
    - p21b_t24_f7
  simple:
    - p21b_t02
    - p21b_t03
    - p21b_t04
    - p21b_t05
    - p21b_t26
    - p21b_t27
    - p21b_t28
    - p21b_t29
p22:
  simple:
    - p22b_t02
    - p22b_t03
    - p22b_t04
    - p22b_t05
    - p22b_t07
    - p22b_t08
    - p22b_t09
    - p22b_t10
    - p22b_t17_f1
    - p22b_t18_f1
    - p22b_t19_f1
    - p22b_t21_f2
    - p22b_t22_f2
    - p22b_t23_f2
    - p22b_t25_f3
    - p22b_t26_f3
    - p22b_t27_f3
    - p22b_t29_f4
    - p22b_t30_f4
    - p22b_t31_f4
p23:
  text:
  simple:
    - p23b_t02
    - p23b_t03
    - p23b_t04
    - p23b_t05
    - p23b_t07
    - p23b_t08
    - p23b_t09
    - p23b_t10
p24:
  text:
  simple:
    - p24b_t02
    - p24b_t03
    - p24b_t04
    - p24b_t05
    - p24b_t08
    - p24b_t09
    - p24b_t10
    - p24b_t11
 
  libre-l:   
    - p24b_t13
p25:
  text:
  simple:
    - p25b_t03
    - p25b_t04
    - p25b_t05
    - p25b_t06
    - p25b_t09
    - p25b_t10
    - p25b_t11
    - p25b_t12
p26:
  text:
  libre-l:   
    - p26b_t03
    - p26b_t04
    - p26b_t05
  simple:
    - p26b_t14_f1
    - p26b_t15_f1
    - p26b_t17_f2
    - p26b_t18_f2
    - p26b_t20_f3
    - p26b_t21_f3
    - p26b_t23_f4
    - p26b_t24_f4
    - p26b_t26_f5
    - p26b_t27_f5
p27:
  text:
  simple:
    - p27b_t06_f1
    - p27b_t07_f1
    - p27b_t09_f2
    - p27b_t10_f2
    - p27b_t12_f3
    - p27b_t13_f3
    - p27b_t15_f4
    - p27b_t16_f4
    - p27b_t18_f5
    - p27b_t19_f5
p28:
  text:
  simple:
    - p28b_t02
    - p28b_t03
    - p28b_t04
    - p28b_t05
    - p28b_t08
    - p28b_t09
    - p28b_t10
    - p28b_t11
    - p28b_t13
    - p28b_t14
    - p28b_t15
    - p28b_t16
p29:
  text:
  simple:
    - p29b_t03
    - p29b_t04
    - p29b_t05
    - p29b_t06
p30:
  text:
  simple:
    - p30b_t02
    - p30b_t03
    - p30b_t04
    - p30b_t05
    - p30b_t07
    - p30b_t08
    - p30b_t09
    - p30b_t10
p31:
  text:
  simple:
    - p31b_t02
    - p31b_t03
    - p31b_t04
    - p31b_t05
    - p31b_t07
    - p31b_t08
    - p31b_t09
    - p31b_t10
p32:
  text:
  simple:
    - p32b_t02
    - p32b_t03
    - p32b_t04
    - p32b_t05
p33:
  text:
  simple:
    - p33b_t05_f1
    - p33b_t06_f1
    - p33b_t08_f2
    - p33b_t09_f2
    - p33b_t11_f3
    - p33b_t12_f3
    - p33b_t14_f4
    - p33b_t15_f4
    - p33b_t17_f5
    - p33b_t18_f5
    - p33b_t20_f6
    - p33b_t21_f6
p34:
  text:
  libre-s:
    - p34b_t05_f1
    - p34b_t07_f2
    - p34b_t09_f3
    - p34b_t11_f4