
pageImages:
  p00:
    - p00a_izq_t04_t05_30_img.png
  p01:
    - p01a_cen_t03_t03_40_img.png
  p02:
    - p02a_cen_t03_t03_30_img.png
  p03:
    - p03a_cen_t05a_t05a_30_img.png
    - p03a_cen_t06b_t06b_30_img.png
  p04:
    - p04a_cen_t05a_t05a_30_img.png
    - p04a_cen_t06b_t06b_30_img.png
    - p04b_cen_t02_t02_100_img.png
    - p04b_cen_t03_t03_100_img.png
    - p04b_cen_t04_t04_100_img.png
    - p04b_cen_t05_t05_100_img.png
  p05:
    - p05a_dch_t03_t03_25_img.png
    - p05a_izq_t10_t18_25_img.png
  p06:
    - p06a_dch_t03_t03_25_img.png
    - p06a_izq_t10_t18_25_img.png
  p07:
    - p07a_dch_t03_t03_25_img.png
    - p07a_izq_t10_t18_25_img.png
  p08:
    - p08a_cen_t02_t02_100_img.png
    - p08a_cen_t03_t03_80_img.png
    - p08a_cen_t04_t04_100_img.png
    - p08a_cen_t05_t05_100_img.png
  p09:
    - p09a_cen_t02_t02_100_img.png
    - p09a_cen_t03_t03_80_img.png
    - p09a_cen_t04_t04_100_img.png
    - p09a_cen_t05_t05_100_img.png
  p10:
    - p10a_cen_t03_t03_100_img.png
    - p10a_cen_t04_t04_100_img.png
  p11:
    - p11a_cen_t03_t03_100_img.png
    - p11a_cen_t04_t04_100_img.png
  p12:
    - p12b_cen_t01_t01_60_img.jpg
pageOptionReplaces:
  p10: # Page where any replace's being done
    p10b_t04: # Option code
      parameters: {disabled: true, enabled: true, type: checkbox}  # Parameter(s) for the replacing template
      template: 'field/input.html.twig' # Templates' location path (TEMPLATE_FILES_DIR relative)
pageAudios:
  p01:
    - p01a_cen_t09_t09_x3_eus.mp3
  p02:
    - p02a_cen_t05_t05_x3_eus.mp3
pageTitles:
  - p00a_t00
  - p00a_t02
  - p00b_t01
  - p01a_t01
  - p01a_t10
  - p02a_t01
  - p02a_t06
  - p03a_t01
  - p03a_t04
  - p04a_t01
  - p04a_t04
  - p05a_t00
  - p05a_t02
  - p06a_t02
  - p07a_t02
  - p08a_t00
  - p08a_t02
  - p09a_t02
  - p10a_t01
  - p10a_t03
  - p11a_t03
  - p12b_t03
pageAreaWidths:
  p04:
    a: 60
  p05:
    a: 60
  p06:
    a: 60
  p07:
    a: 60
  p10:
    a: 60
    b: 40
  p11:
    a: 60
    b: 40
  p12:
    b: 100
totalPages: 12