
pageImages:
  p00:
    - p00a_izq_t04_t05_30_img.png
  p01:
    - p01a_cen_t01_t01_50_img.png
  p02:
    - p02a_cen_t03_t03_30_img.png
  p03:
    - p03a_cen_t04_t04_80_img.png
    - p03a_cen_t05_t05_80_img.png
  p04:
    - p04a_cen_t04_t04_80_img.png
    - p04a_cen_t05_t05_80_img.png
  p05:
    - p05a_dch_t03_t03_25_img.png
    - p05a_izq_t10_t18_25_img.png
  p06:
    - p06a_dch_t03_t03_25_img.png
    - p06a_izq_t10_t18_25_img.png
  p07:
    - p07a_dch_t03_t03_25_img.png
    - p07a_izq_t10_t18_25_img.png
  p08:
    - p08a_dch_t07_t07_25_img.png
    - p08a_izq_t03_t05_25_img.png
  p09:
    - p09a_dch_t07_t07_25_img.png
    - p09a_izq_t03_t05_25_img.png
  p10:
    - p10a_dch_t07_t07_25_img.png
    - p10a_izq_t03_t05_25_img.png
  p11:
    - p11a_dch_t04_t11_30_img.png
  p12:
    - p12a_dch_t04_t11_30_img.png
  p13:
    - p13a_dch_t04_t11_30_img.png
  p14:
    - p14b_cen_t01_t01_60_img.jpg

pageTextReplaces:
  p10:
    p10b_t02:
      parameters: {  }
      template: 'partial/fields/input.html.twig'
    p10b_t03:
      parameters: {  }
      template: 'partial/fields/input.html.twig'
    p10b_t04:
      parameters: {  }
      template: 'partial/fields/input.html.twig'
    p10b_t05:
      parameters: {  }
      template: 'partial/fields/input.html.twig'

pageAudios:
  p01:
    - p01a_cen_t06_t06_x3_eus.mp3
  p02:
    - p02a_cen_t05_t05_x3_eus.mp3
  
pageTitles:
  - p00a_t01
  - p00a_t02
  - p00b_t01
  - p01a_t01
  - p01a_t06
  - p02a_t01
  - p02a_t02
  - p02a_t05
  - p03a_t01
  - p03a_t04
  - p04a_t04
  - p05a_t00
  - p05a_t02
  - p06a_t02
  - p07a_t02
  - p08a_t00
  - p08a_t02
  - p09a_t02
  - p10a_t02
  - p11a_t01
  - p11a_t03
  - p12a_t01
  - p12a_t03
  - p13a_t01
  - p13a_t03
  - p14b_t03

pageAreaWidths:
  p14:
    b: 100

totalPages: 14