
pageTitles: # All centered texts' codes
  - p00b_t01
  - p01b_t01
  - p05b_t03
  - p06b_t01
  - p10b_t17

pageAreaWidths:
  p00:  # Page affected with any custom side-width
    b: 100  # side-letter: window-relative-width-percentage
  p01:
    b: 100
  p02:
    b: 100
  p03:
    b: 100
  p04:  
    b: 100
  p05:  
    b: 100
  p06:  
    b: 100
  p07:  
    b: 100
  p08:
    b: 100
  p09:  
    b: 100
  p10:  
    b: 100

pageOptionRequired: # All required item texts' codes
  p11:
    - p00b_t18_c0
    - p00b_t20_c1
    - p00b_t22_c2
    - p00b_t24_c3
    - p00b_t26_c4
    - p00b_t30_c0
    - p00b_t32_c1
    - p00b_t34_c2
    - p00b_t36_c3
    - p00b_t38_c4
    - p00b_t40_c5

totalPages: 10  # The final total pages