
pageImages:

pageTitles: # All centered texts' codes
  - p00b_t01
  - p01b_t01

pageTextReplaces:

pageAreaWidths:
  p00:  # Page affected with any custom side-width
    b: 100  # side-letter: window-relative-width-percentage
  p01:
    b: 100
  p02:
    b: 100
  p03:
    b: 100
  p04:  
    b: 100

# TODO: being dynamic
totalPages: 10  # The final total pages