
pageImages:
  p00:
    - p00b_cen_t06_t06_40_img.png
  p01:
    - p01a_cen_t03_t03_60_img.png
  p02:
    - p02a_cen_t02_t02_30_img.png
  p03:
    - p03b_cen_t02_t02_40_img.png
  p04:
    - p04a_cen_t01_t01_100_img.png
  p05:
    - p05a_izq_t06_t07_40_img.png
  p06:
    - p06a_izq_t04_t06_50_img.png
    - p06a_izq_t10_t11_30_img.png
  p07:
    - p07b_cen_t01_t01_60_img.jpg

pageAudios:
  p01:
    - p01a_cen_t06_t06_x2_eus.mp3
    - p01a_cen_t06_t06_x2_eus.ogg
  p02:
    - p02a_cen_t05_t05_x2_eus.mp3
    - p02a_cen_t05_t05_x2_eus.ogg

pageTitles:
  - p00b_t01
  - p01a_t01
  - p01a_t03
  - p01a_t06
  - p02a_t01
  - p02a_t05
  - p03b_t01
  - p04a_t01
  - p05a_t02
  - p05b_t00
  - p06a_t02
  - p06b_t00
  - p07b_t03
  
pageAreaWidths:
  p00:
    b: 100
  p03:
    b: 100
  p04:
    b: 40
  p07:
    b: 100

totalPages: 7