p01:
  text:
  simple:
    - p01b_t03
    - p01b_t04
    - p01b_t05
    - p01b_t06
    - p01b_t08
    - p01b_t09
    - p01b_t10
    - p01b_t11
p02:
  text:
  simple:
    - p02b_t03
    - p02b_t04
    - p02b_t05
    - p02b_t06
p03:
  simple:
    - p03b_t02
    - p03b_t03
    - p03b_t04
    - p03b_t05
    - p03b_t07
    - p03b_t08
    - p03b_t09
    - p03b_t10
p04:
  simple:
    - p04b_t02
    - p04b_t03
    - p04b_t04
    - p04b_t05
    - p04b_t08
    - p04b_t09
    - p04b_t10
    - p04b_t11
p05:
  simple:
    - p05b_t03
    - p05b_t04
    - p05b_t05
    - p05b_t06
p06:
  simple:
    - p06b_t02
    - p06b_t03
    - p06b_t04
    - p06b_t05
    - p06b_t08
    - p06b_t09
    - p06b_t10
    - p06b_t11
p07:
  text:
  simple:
    - p07b_t03
    - p07b_t04
    - p07b_t05
    - p07b_t06
p08:
  text:
  simple:
    - p08b_t03
    - p08b_t04
    - p08b_t05
    - p08b_t06
p09:
  text:
  simple:
    - p09b_t02
    - p09b_t03
    - p09b_t04
    - p09b_t05
    - p09b_t08
    - p09b_t09
    - p09b_t10
    - p09b_t11
p10:
  text:
  simple:
    - p10b_t02
    - p10b_t03
    - p10b_t04
    - p10b_t05
    - p10b_t07
    - p10b_t08
    - p10b_t09
    - p10b_t10
p11:
  text:
  simple:
    - p11b_t02
    - p11b_t03
    - p11b_t04
    - p11b_t05
p12:
  text:
  simple:
    - p12b_t02
    - p12b_t03
    - p12b_t04
    - p12b_t05
    - p12b_t07
    - p12b_t08
    - p12b_t09
    - p12b_t10
    - p12b_t13
    - p12b_t14
    - p12b_t15
    - p12b_t16
p13:
  simple:
    - p13b_t03
    - p13b_t04
    - p13b_t05
    - p13b_t06
p14:
  simple:
    - p14b_t02
    - p14b_t03
    - p14b_t04
    - p14b_t05
    - p14b_t07
    - p14b_t08
    - p14b_t09
    - p14b_t10
    - p14b_t12
    - p14b_t13
    - p14b_t14
    - p14b_t15
p15:
  simple:
    - p15b_t03
    - p15b_t04
    - p15b_t05
    - p15b_t06
p16:
  simple:
    - p16b_t03
    - p16b_t04
    - p16b_t05
    - p16b_t06
p17:
  simple:
    - p17b_t03
    - p17b_t04
    - p17b_t05
    - p17b_t06
p18:
  simple:
    - p18b_t03
    - p18b_t04
    - p18b_t05
    - p18b_t06
