
# Database codes' map
codes:
  lh617probak:
    # Eusk
    lh617_testuak_lh_eusa:        lh617_eusa
    lh617_testuak_lh_eusbd:       lh617_eusbd
    # Gazte
    lh617_testuak_gaz_a:          lh617_gaz_a
    lh617_testuak_gaz_b:          lh617_gaz_b
    lh617_testuak_gaz_c:          lh617_gaz_c
    # Inge
    # Mate
    # Zie
    # G. sortak
  ed17probak:
    # Eusk
    edg051_testuak_dbh_eusa:      ed17_dbh_eusa
    edg051_testuak_dbh_eusbd:     ed17_dbh_eusbd
    edg051_testuak_lh_eusa:       ed17_lh_eusa
    edg051_testuak_lh_eusbd:      ed17_lh_eusbd
    # Gazte
    edg051_testuak_dbh_gaz:       ed17_dbh_gaz
    edg051_testuak_lh_gaz:        ed17_lh_gaz
    # Inge
    edg051_testuak_dbh_ing:       ed17_dbh_ing
    edg051_testuak_lh_ing:        ed17_lh_ing
    # Mate
    edg051_testuak_dbh_mat:       ed17_dbh_mat
    edg051_testuak_lh_mat:        ed17_lh_mat
    # Zie
    edg051_testuak_dbh_zie:       ed17_dbh_zie
    edg051_testuak_lh_zie:        ed17_lh_zie
    # G. sortak
    edg051_testuak_dbh_gsorta_a:  ed17_dbh_gso_a
    edg051_testuak_dbh_gsorta_b:  ed17_dbh_gso_b
    edg051_testuak_dbh_gsorta_c:  ed17_dbh_gso_c
    edg051_testuak_lh_gsorta_a:   ed17_lh_gso_a
    edg051_testuak_lh_gsorta_b:   ed17_lh_gso_b
    edg051_testuak_lh_gsorta_c:   ed17_lh_gso_c
    # Simul
    edg051_testuak_dbh_simul:     ed17_dbh_simul