
# Database access configuration
credentials:
  lh617probak:
    # Eusk
    LH6EUS:
      a:    lh617_testuak_eus_a
      b:    lh617_testuak_eus_b
      c:    lh617_testuak_eus_c
    # Gazte
    LH6GAZ:
      a:    lh617_testuak_gaz_a
      b:    lh617_testuak_gaz_b
      c:    lh617_testuak_gaz_c
    # Inge
    LH6ING:
      a:    lh617_testuak_ing_a
      b:    lh617_testuak_ing_b
      c:    lh617_testuak_ing_c
    # Mate
    LH6MAT:
      a:    lh617_testuak_mat_a
      b:    lh617_testuak_mat_b
      c:    lh617_testuak_mat_c
    # Zie
    LH6ZIE:
      a:    lh617_testuak_zie_a
      b:    lh617_testuak_zie_b
      c:    lh617_testuak_zie_c
  ed17probak:
    # Eusk
    EB2746:
      a:    edg051_testuak_dbh_eusa
      bd:   edg051_testuak_dbh_eusbd
    EL2963:
      a:    edg051_testuak_lh_eusa
      bd:   edg051_testuak_lh_eusbd
    # Gazte
    CB3736: edg051_testuak_dbh_gaz
    CL2528: edg051_testuak_lh_gaz
    # Inge
    IB3896: edg051_testuak_dbh_ing
    IL8027: edg051_testuak_lh_ing
    # Mate
    MB0406: edg051_testuak_dbh_mat
    ML4612: edg051_testuak_lh_mat
    # Zie
    ZB6432: edg051_testuak_dbh_zie
    ZL2428: edg051_testuak_lh_zie
    # G. sortak
    GB3479:
      a:    edg051_testuak_dbh_gsorta_a
      b:    edg051_testuak_dbh_gsorta_b
      c:    edg051_testuak_dbh_gsorta_c
    GL0615:
      a:    edg051_testuak_lh_gsorta_a
      b:    edg051_testuak_lh_gsorta_b
      c:    edg051_testuak_lh_gsorta_c
    # Simul
    SB2017: edg051_testuak_dbh_simul