
# Database tables' map
targets:
  lh617probak:
    # Eusk
    lh617_testuak_eus_a:          erantzunak_eus_a
    lh617_testuak_eus_b:          erantzunak_eus_b
    lh617_testuak_eus_c:          erantzunak_eus_c
    # Gazte
    lh617_testuak_gaz_a:          erantzunak_gaz_a
    lh617_testuak_gaz_b:          erantzunak_gaz_b
    lh617_testuak_gaz_c:          erantzunak_gaz_c
    # Inge
    lh617_testuak_ing_a:          erantzunak_ing_a
    lh617_testuak_ing_b:          erantzunak_ing_b
    lh617_testuak_ing_c:          erantzunak_ing_c
    # Mate
    lh617_testuak_mat_a:          erantzunak_mat_a
    lh617_testuak_mat_b:          erantzunak_mat_b
    lh617_testuak_mat_c:          erantzunak_mat_c
    # Zie
    lh617_testuak_zie_a:          erantzunak_zie_a
    lh617_testuak_zie_b:          erantzunak_zie_b
    lh617_testuak_zie_c:          erantzunak_zie_c
  ed17probak:
    # Eusk
    edg051_testuak_dbh_eusa:      erantzunak_dbh_eusa
    edg051_testuak_dbh_eusbd:     erantzunak_dbh_eusbd
    edg051_testuak_lh_eusa:       erantzunak_lh_eusa
    edg051_testuak_lh_eusbd:      erantzunak_lh_eusbd
    # Gazte
    edg051_testuak_dbh_gaz:       erantzunak_dbh_gaz
    edg051_testuak_lh_gaz:        erantzunak_lh_gaz
    # Inge
    edg051_testuak_dbh_ing:       erantzunak_dbh_ing
    edg051_testuak_lh_ing:        erantzunak_lh_ing
    # Mate
    edg051_testuak_dbh_mat:       erantzunak_dbh_mat
    edg051_testuak_lh_mat:        erantzunak_lh_mat
    # Zie
    edg051_testuak_dbh_zie:       erantzunak_dbh_zie
    edg051_testuak_lh_zie:        erantzunak_lh_zie
    # G. sortak
    edg051_testuak_dbh_gsorta_a:  erantzunak_dbh_gsorta_a
    edg051_testuak_dbh_gsorta_b:  erantzunak_dbh_gsorta_b
    edg051_testuak_dbh_gsorta_c:  erantzunak_dbh_gsorta_c
    edg051_testuak_lh_gsorta_a:   erantzunak_lh_gsorta_a
    edg051_testuak_lh_gsorta_b:   erantzunak_lh_gsorta_b
    edg051_testuak_lh_gsorta_c:   erantzunak_lh_gsorta_c
    # Simul
    edg051_testuak_dbh_simul:     erantzunak_dbh_simul