
# Database tables' map
targets:
  lh617probak:
    # Eusk
    # Gazte
    lh617_testuak_gaz_a:          erantzunak_gaz_a
    # Inge
    # Mate
    # Zie
    # G. sortak
  ed17probak:
    # Eusk
    edg051_testuak_dbh_eusa:      erantzunak_dbh_eusa
    edg051_testuak_dbh_eusbd:     erantzunak_dbh_eusbd
    edg051_testuak_lh_eusa:       erantzunak_lh_eusa
    edg051_testuak_lh_eusbd:      erantzunak_lh_eusbd
    # Gazte
    edg051_testuak_dbh_gaz:       erantzunak_dbh_gaz
    edg051_testuak_lh_gaz:        erantzunak_lh_gaz
    # Inge
    edg051_testuak_dbh_ing:       erantzunak_dbh_ing
    edg051_testuak_lh_ing:        erantzunak_lh_ing
    # Mate
    edg051_testuak_dbh_mat:       erantzunak_dbh_mat
    edg051_testuak_lh_mat:        erantzunak_lh_mat
    # Zie
    edg051_testuak_dbh_zie:       erantzunak_dbh_zie
    edg051_testuak_lh_zie:        erantzunak_lh_zie
    # G. sortak
    edg051_testuak_dbh_gsorta_a:  erantzunak_dbh_gsorta_a
    edg051_testuak_dbh_gsorta_b:  erantzunak_dbh_gsorta_b
    edg051_testuak_dbh_gsorta_c:  erantzunak_dbh_gsorta_c
    edg051_testuak_lh_gsorta_a:   erantzunak_lh_gsorta_a
    edg051_testuak_lh_gsorta_b:   erantzunak_lh_gsorta_b
    edg051_testuak_lh_gsorta_c:   erantzunak_lh_gsorta_c
    # Simul
    edg051_testuak_dbh_simul:     erantzunak_dbh_simul